### ISSUE TITLE
What should the structure of commands for managing Shares be?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#10]
This is a bit of a design question with fairly broad implications for a bunch of commands.

There's some clunkiness regarding shared endpoint management because they're _sorta_ endpoints and they're _sorta_ their own thing.
That they are valid logical endpoints, good as Task and FS op targets, is good and useful, but only if we strip back the meaning of "endpoint" to be exactly that.
Shared Endpoints don't/can't support the full set of Endpoint operations, which makes managing them as a type of endpoint very weird.

That leads to real weirdness in the API as well -- like all endpoints having a nullable "host_path" field.
At the very least, it would be nice to have endpoint subtypes added, so that we're not deducing the endpoint type from which fields are null.

Ideally, in my mind, non-shared endpoints would be "demoted" to be another specialized type of endpoint, something like "physical endpoints" or "gridftp server endpoints" (which distinguishes them from S3), but that's a bigger issue.
For now, focusing on the CLI.

I started looking at #3 again, and realized that there's actually a bit of a model problem posed here.
Regarding shared endpoint creation in particular, I think we have three options.
  1. `globus transfer endpoint create --shared --host-endpoint-id ...`
  2. `globus transfer endpoint share --host-endpoint-id ...`
  3. `globus transfer share create --host-endpoint-id ...`

If I had to distill down this issue to a TL;DR format, it would probably be a choice between those three options, phrased as
Conceptually, which of the following is a Share?

  1. A Special Type of Endpoint
  2. A Resource Belonging to an Endpoint
  3. A First-Class Entity (which happens to depend on an Endpoint)

How we think of Shared Endpoints / Shares and "what they are" will ultimately drive how we present them and manage them in the CLI and potentially other interfaces.

Right now, the API and Web App share the opinion that a Shared Endpoint is a special kind of endpoint. That works really well when you're looking at endpoints that are shared with you, but very badly when you're trying to manage your own shared endpoints.

Should this be divided into two categories?
I would be most inclined towards:

  - Your own Shared Endpoints are first-class objects which require a host-endpoint as a dependency
  - Shared Endpoints not owned by you (and even your own when found in searches) are a special case of Endpoints

That duality could be confusing if poorly presented, but I think the other split-brained view of the world -- in which managing Shared Endpoints is a confusing special case of managing an endpoint definition -- is more confusing.
Perhaps the Web UI will continue with its current layout and format, but the CLI, SDK, and other developer tools will present things in a different form? I worry that inconsistency will confuse developers by not mapping nicely to the UI, but right now we'll be confusing developers anyway, so it's not exactly a net loss.

I can take whatever kind of decision I want for now, but this needs to be resolved properly before the first "production" version.

**Comment by bd4** [comment]
I like (3) making it's own first class entity command. That's basically how it's modeled in the REST API, because it has it's own separate factory for creation. The downside of that is that manipulating a shared ep uses the endpoint command structure, because it really is an endpoint, but still seems like the most convenient structure to me. The same issue exists in the REST API.

**Comment by sirosen** [comment]
Yeah, I think we need to solve this better in the API than we have to-date.
It has a first-class C, but second-class RUD, of the CRUD operations.
It's somewhat telling that Shared Endpoints are a section of the https://docs.globus.org/api/transfer/endpoint documentation page.

@bd4, is there a better way of checking if an endpoint is shared other than looking for its "host_endpoint" field?
Maybe I should open a feature request against the API for a `DATA_SUBTYPE` field which is a string (or object?) full of info on what kind of `DATA_TYPE` an API response really is?
Alternatively, we could implement this logic in a nicely centralized way in the SDK, but that gets messy with the mix of direct endpoint documents wrapped in `TransferResponse`s and the `PaginatedResource` we get from endpoint search.

Pushing forward on the thinking in which we do `globus transfer share *`.

In terms of modeling it as a separate command, I think that all of the endpoint manipulation commands that are duplicated (like deletion) just need a little bit of special-casing to print a message directing users to do the "right thing" next time.
Example:
```shell
$ globus transfer endpoint delete --endpoint-id abc123
warning:
  abc123 was a shared endpoint.
  We recommend deleting shared endpoints with
    globus transfer share delete --share-id abc123

Successfully deleted Endpoint abc123 (MyFancyShareDisplayName)
```

So warn, but still proceed with the operation.

Related question: should `globus transfer share *` commands use `--endpoint-id` or a new param like `--share-id`?
I think it should be `--share-id` to reinforce the notion that a Share is a first-class entity.
Docs can state that `--share-id` is an `--endpoint-id` under the hood.

Some of my internal bits and pieces for handling endpoints (like my fancy [create/update args decorator](https://github.com/globus/globus-cli/blob/master/globus_cli/services/transfer/endpoint/helpers.py)) are decently portable with minimal effort to this model, which I like.

**Comment by bd4** [comment]
Shared endpoints are fundamentally messy to model, I can't think of anything better than the C/RUD split approach we have now. Trying to shove them into standard endpoint C would be conceptually cleaner, but worse in practice I think. Having a completely separate CRUD for shared eps would just be annoying for clients.

Re having a cleaner way of specifying shared/gcp eps, we could add a general DATA_SUBTYPE, or a more specify endpoint_type fields. I'm torn - I think periodically trying to clean up the API is nice, but real world forces always make it messy again, no matter what you do. So how much does it really help clarify what's going on? I guess if we add a type field, we can make it clear in the doc that new types may be introduced in the future. Strict enum fields (e.g. task status) become less useful over time.

**Comment by sirosen** [comment]
Task Status is a nice example of a strict enum that has reached its limits.
Why not an enum which we don't restrict like that, however?

I somewhat disagree about having shared endpoints being a separate CRUD API being a pain for clients. I think we should either completely unify them, or completely split them off.
The current half-combined state is, I think, the worst of all possible worlds for clients. They need to cope with shared endpoints being endpoints in their model, but then remember to use a different creation resource.
I think this is much more of a pain than an entirely separate API -- although I agree that there is a good model in which they are part of the same set of resources.

My own inclination is to have a single set of REST resources for all endpoint types, but omit many, many of the fields that we're returning for endpoints for which they don't apply.
For a shared endpoint or a GCP endpoint, the signal-to-noise ratio is so poor that I'm tempted to make wrapper classes that extract only the desirable fields in order to clarify what is important.

I think we need to consider a complete revision of endpoint documents, restructured to fit the growing complexity here. Shared Endpoints could fit into that model very well.

For example, this would be nice to see:
```yaml
# base endpoint document
{
  "DATA_TYPE": "endpoint",
  "endpoint_type": ...,
  "endpoint_id": "...",
  "display_name": "...",
  ...
}
# shared endpoint
{
  "DATA_TYPE": "endpoint",
  "endpoint_type": "share",
  "endpoint_id": "...",
  "display_name": "...",
  "host_endpoint_id": "...",
  "host_path": "...",
  ...
}
# gcp endpoint
{
  "DATA_TYPE": "endpoint",
  "endpoint_type": "globus_connect_personal",
  "globus_connect_setup_key": "...",
  ...
}
```

Right now, I have `gcp_connected` fields on my shared endpoints. To me, as a consumer of the API, that's not just inconvenient -- it's wrong. It states that "this is a meaningful field for all endpoints", when it clearly isn't.

I think we should either consider a special field like `endpoint_type`, or a generalized version of that, like
```yaml
{
  "DATA_TYPE": "xyz",
  "SUBTYPE": "yyz",
  ...
}
```

The notion of `endpoint_type="share"` is, I think, consistent with the model of Shares being first class entities, with a dual notion that "All Shares are valid Endpoints".

@bd4 I think we've left behind the CLI-specific discussion a bit. Would you like to continue this elsewhere as a discussion of the Transfer API?

---

I think we settled pretty quickly on the idea of `globus transfer share (create|show|delete|...)` as our way of interacting with shared endpoints.

A few questions remain that I think need resolution.

- Should the CLI expose the fact that you're working with an endpoint definition explicitly? This will, of course, be clear to anyone who looks at the API responses. It's a question of using `--share-id` vs. `--endpoint-id` to display a shared endpoint.
- When shared endpoint commands are used on non-shared endpoints, should the CLI throw an error, or just warn?
- When normal endpoint commands are used on shared endpoints, should the CLI throw an error, wran, or do nothing special?

Importantly, how does this impact the existing ACL commands like `acl list`?
If we start using `--share-id`, should `globus transfer acl list` take a `--share-id` or an `--endpoint-id`?
It's important to know that Shares are a type of Endpoint, and that `--share-id`s are valid `--endpoint-id`s, and although that intuitively argues for using `--endpoint-id` everywhere, I think it's very confusing to read `globus transfer share show --endpoint-id`.

**Comment by bd4** [comment]
Shared endpoints are a type of endpoint, and I don't think we should try to hide that fact. I like using `--endpoint-id` everywhere, and never use `--share-id`.

Created an issue for further Transfer API discussion:
https://github.com/globusonline/transfer-api/issues/22
