### ISSUE TITLE
Support for ^Bookmark syntax

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#105]
@tuecke

> Why not support the same ^bookmark functionality in the new CLI? That was the result of a LOT of discussion in the ssh CLI, and is much more user friendly than your proposed solution.

Here's what I remember from when we last talked about the ^Bookmark syntax to support it:
- [ ] research how to correctly handle escaping, including spaces, circumflexes, slashes, colons
  - [ ] do we provide a helper for script writers to escape human input?
- [ ] research how this works when combined with paths, including issues with relative paths
- [ ] research how to implement this as an argument type in the Click framework such that it is resolved to an endpoint UUID/path pair once the body of the function fires
- [ ] decide if we keep the `bookmark locate` method (this method requires no escaping for someone handling user input, for example, whereas the ^Bookmark method would)

**Comment by sirosen** [comment]
I always hated that syntax and thought it was messy, confusing (as a consumer of the CLI), and model-breaking.
In my own opinion, removing it and replacing it with explicit bookmark resolution is a vast improvement.

Keeping in mind that the SSH CLI couldn't natively support subshells, I'm not convinced that a past discussion of it in the hosted CLI applies to the new product.
In fact, even if it could, I think the complexity introduced by this makes it a mistake.

Simple example: consider a pair bookmark names which themselves contains colons.
`tut:ep1 -> Globus Tutorial Endpoint 1:/~/`
`tut:ep1:myhome -> Globus Tutorial Endpoint 1:/~/`
If we see this embedded in a command line, even with the caret, it won't resolve unambiguously. What does `^tut:ep1:myhome:otherdir` actually mean? It could refer to `/~/otherdir` or to `/~/myome:otherdir`. There is no possible way to know.

We would have to delimit the start and end of a bookmark name, and offer escaping of our end delimiter. Consider the form of the syntax that looks like `^(BookmarkName)`, intended to solve the above ambiguity.
How do we protect against `BookmarkName` containing right parens? We would need to offer the capability for users to escape those parens, meaning that anyone building on this can't feed us user-input directly but needs to escape it carefully and the parsing gets more complicated. The removal of escapes from many parts of the interface is one of the great boons of the new product, and I am very much loathe to give it up casually.

These are just the first problems that surface off the top of my head.

I would much sooner support a form of `EndpointPlusPath` consuming commands in which the endpoint is optional (discarded if present?) and we allow an option to do the work of `bookmark locate`. For example, `--bookmark BookmarkNameOrId` easily and safely resolves bookmarks to endpoint-plus-path types, properly communicates to anyone reading a script that they are operating on a bookmark, not a raw endpoint, and, if we pursue bookmark name completion, is complete-able.

**Comment by sirosen** [comment]
Rachana is going to investigate this further, so assigning to her.

**Comment by sirosen** [comment]
Replaced by #369
