### ISSUE TITLE
Unable to scan endpoint

### ISSUE THREAD

**Issue by cug-zmm** [globus/globus-cli#1061]
Hi,
This is my first time to try to download data from globus and I meet a strange error. So I need your help!
I want to download the data in my school cluster so I install globus and globus-cli and their states have been connected.

![1733712193454](https://github.com/user-attachments/assets/c3288fa8-9e57-40dc-a610-bc72e4a8506a)
 
But when I have set the ep1 and ep2 and tried to download the data, it couldn't work.

Globus CLI Error: A Transfer API Error Occurred.
HTTP status:      502
request_id:       VB7juVFae
code:             ExternalError
message:          Unable to scan endpoint (1, 'Error (connect)\nEndpoint: eoas_henry (0eb73b0a-b495-11ef-8890-f349fadc53c5)\nServer: Globus Connect\nMessage: The server may be too busy\n---\nDetails: an end-of-file was reached\\nglobus_xio: The GSI XIO driver failed to establish a secure connection. The failure occured during a handshake read.\\nglobus_xio: An end of file occurred\\n\n')

I want to know how I can solve this issue.

Very thanks for your work!

**Comment by sirosen** [comment]
Hi there!

The error message is coming from an attempt to reach your Globus Connect Personal endpoint. `eoas_henry (0eb73b0a-b495-11ef-8890-f349fadc53c5)` is not reachable. I think we should focus any diagnostic effort on that endpoint.

Are you able to run `globus ls 0eb73b0a-b495-11ef-8890-f349fadc53c5` successfully? I see from your screenshot that it reports itself as connected, but I wonder if it is unresponsive, based on the error. You might be able to run Globus Connect Personal with the `-debug` flag to get more information, but I'll note that it's very verbose when things are working, so don't be surprised if you get a lot of output.

As this isn't an issue specific to the globus CLI, I think it might be best if you reached out to us via support@globus.org . If you do, I can direct you to the team that maintains the transfer service -- they're probably the ones best equipped to help you.

**Comment by cug-zmm** [comment]
Hi sirosen,

I modify the cluster and now I can transfer the data. My supervisor told me this might be because the first cluster has many limitations, such as network and host firewall. 

Very thanks for your reply and help!

**Comment by sirosen** [comment]
I'm marking this resolved, but don't hesitate to file another issue if you have trouble with the CLI, or a support ticket if you need help with our services!
