### ISSUE TITLE
Updating an endpoint with --myproxy-server or --oauth-server should probably clear the other one

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#108]
Today, if you have an endpoint with `oauth_server` set, which Transfer prefers over `myproxy_server`, it's not possible to get the endpoint back to a MyProxy setup using `--myproxy-server` because the `oauth_server` value will be left set. Further, it's not possible to clear it explicitly using something like `--myproxy-server=''` or `--no-myproxy-server`.

Additionally, specifying these longargs together should probably be considered an error.

**Comment by corpulentcoffee** [comment]
How would folks feel about just fixing this in the SDK's `TransferClient`?

- both `create_endpoint()` and `update_endpoint()` could raise an exception if both `data['myproxy_server'] and data['oauth_server']` are set
- `update_endpoint()` could set `data['myproxy_server'] = None` if `data['oauth_server']` is set, and vice versa [if neither is set, it would just leave them alone]

This seems like much less work than trying to fix it in the CLI, particularly since these fields go away when the activation system changes.

**Comment by sirosen** [comment]
In an ideal world we'd do all of this enforcement server-side, but pushing it "down the stack" into the SDK seems better than trying to do something specialized in the CLI. I'm in favor of this approach.

**Comment by corpulentcoffee** [comment]
OK, I'll take this.
