### ISSUE TITLE
Add `config` command for setting up and modifying the `~/.globus.cfg`

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#12]
This was a feature request I got from Steve -- he seemed to feel pretty strongly about it being a necessary intro point.

My instinct is that semantics should be somewhere between what `knife configure` and `git config` offer.

So, `globus config init` (knife-like) should be prompt-oriented and allow users to enter info line by line.
For example,
```shell
$ globus config init
Please enter your auth token: XXXXX
Please enter your transfer token: XXXXX
...
$ globus config init --auth-token XXXXX
Please enter your transfer token: XXXXX
```

However, it might also be useful to have git-like setter/getter functionality. Maybe something more like this:
```shell
$ globus config show general.auth_token # echoes the value
...
$ globus config add general.auth_token XXXXX
```
of course, anything without a dot should be treated as part of the general config section, so these are equivalent to
```shell
$ globus config show auth_token
...
$ globus config add auth_token XXXXX
```
and of course we'd want `globus config remove`

Questions I still have:

1. Should we support a `--system` flag, like `git-config`, to operate on `/etc/globus.cfg` ?
2. Are the verbs "get", "set", and "unset" (like git) or "show", "add", and "remove" (like the other parts of the CLI for endpoints &c.)?
3. Support for `globus config edit` which does `$EDITOR ~/.globus.cfg`?
4. Should the `config` command know that certain values (like tokens) are secret, and show redacted versions of them?
5. What does show/get do when the key is absent? Empty string seems ambiguous -- it's a valid value.
6. What does add/set do when the key is already present? Should there be a `--overwrite` flag?

@bd4 I'm concerned that this needs direct access to the SDK's `GlobusConfigParser`. It's a very unusual internal use-case, and I don't think we want to support it for external groups.
I'm happy to `from globus_sdk.config import GlobusConfigParser`, but I'll need a new function attached to flush its state to a file (the internal `SafeConfigParser` should support this for us), and I'll need to update the `GlobusConfigParser` to support reading only one file. Otherwise, it would load system and default config, and flush all of that back out when it's done, which would be bad.
There are some alternatives:
- Should we do a `0.3.0` of the SDK in which the config parser insists that there is a `[general]` section heading, like a typical `ConfigParser`? Then this would not need the specialized `GlobusConfigParser` at all. That breaks compatibility with existing config, which I don't like. We'd need clear messaging for anyone who has started using it.
- I could make a CLI config parser with implements its own specialized [_read()](https://github.com/globus/globus-sdk-python/blob/master/globus_sdk/config.py#L48)

**Comment by sirosen** [comment]
I discussed this casually with some folks at the CI.
The upshot of that conversation is that we like the following commands:

 - `globus config init`
 - `globus config set`
 - `globus config show`
 - `globus config remove`
 - `globus config edit`

I don't see a strong reason not to use these commands.
We can consider a `--system` flag at a later date.

**Comment by bd4** [comment]
Requiring a `[general]` section seems reasonable to me, especially if users can just do `globus config init` to get the right format.

**Comment by sirosen** [comment]
@bda I took a crack at doing some of these this afternoon and realized that I need to add a new dependency if I want to be able to have this command set work.
Specifically, `configobj` can read and write INI files while preserving comments, whereas the stdlib parser will clobber comments.

I think this is okay, since `configobj` is a well-established library, but I wanted to run it past you to get some thoughts.
Does this seem worth it to you?
