### ISSUE TITLE
Add `--(no-)managed-endpoint` flag or equivalent to `endpoint update`

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#134]
Eric Blau raised this as an issue, and we should be sure to track it somewhere.

Currently, XSEDE is relying on the hosted CLI's
```shell
$ endpoint-modify <endpoint name> --managed-endpoint
```

This is the kind of functionality that seems reasonable to add to `endpoint update`, perhaps under a new name, but there is no API support.
If we can get an API (and corresponding SDK) resource to use, we should add this.

I'm partial to `--managed/--no-managed` as the flag, since `-endpoint` seems redundant.

**Comment by jaswilli** [comment]
What does that option do in the hosted CLI? My understanding is that `super --add-managed-endpoint/--remove-managed-endpoint` sets the status on an endpoint, so what does this do?

**Comment by sirosen** [comment]
@ericblau Can you confirm that `--managed-endpoint` sets an endpoint to be managed?

I assume you have to be a subscription manager for this to work.

**Comment by sirosen** [comment]
@ranantha, is this issue a `1.0` requirement? Or is it something we want shortly after `1.0`?

**Comment by ranantha** [comment]
We don't have block on this for 1.0, but we need this before we can deprecate the current CLI.
