### ISSUE TITLE
Shared endpoints and "endpoint server" commands

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#136]
Should we put some logic into the `endpoint server` commands to make the experience with servers and shared endpoints better?

Currently if you do a `globus endpoint server list <endpoint_id>` on a shared endpoint the CLI will show you the list of servers backing the host endpoint(because the server list is returned by the API) but if you turn around and try to use `globus endpoint server update` you'll get an error message:

```
Globus CLI Error: A Transfer API Error Occurred.
HTTP status:      400
request_id:       LIFg21vsH
code:             BadRequest
message:          That endpoint type doesn't have servers
```

In the web app we don't show servers for shared endpoints and I'm wondering if we shouldn't do the same in the CLI?

**Comment by sirosen** [comment]
Agree that current behavior is bad and should be fixed.

Suggested behavior:

```
$ globus endpoint server list $SHARE_ID

<SHARE_ID> is a Share and does not have Servers

See details for it with
  globus endpoint show <SHARE_ID>

$ echo $?
1
```

**Comment by corpulentcoffee** [comment]
For us to actually know that the UUID the user gave us is a shared endpoint, I assume we're going to have to look up whether it has a `host_endpoint_id` before we make the `endpoint_server_list()` call, e.g.:

```python
host_endpoint_id = client.get_endpoint(endpoint_id,
                                       fields='host_endpoint_id')['host_endpoint_id']
if host_endpoint_id:
    # blah blah blah blah
```

... so maybe it would be nice for us to also include:
```terminal
To see the host's servers, use
  globus endpoint server list <HOST_ID>
```
