### ISSUE TITLE
globus whoami output

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#138]
Removed the "Logged in as: " from the globus whoami output.

Currently its:
$ globus whoami
Logged in as: tuecke@uchicago.edu

Change it to:
$ globus whoami
tuecke@uchicago.edu

This makes it behave more consistently with the system whoami, and makes the output easier to parse and use.

For the verbose output, change the fields names to:

$ globus whoami -v
Username: tuecke@uchicago.edu
Name: Steven Tuecke
Id: b04b1e76-d274-11e5-bf36-07c9790e3d20
Email: tuecke@uchicago.edu

I.e., use "Username:" rather than "Logged in as:"

When not logged in, change the error message to:

$ globus whoami
You are not logged in. Use 'globus login' to login.

**Comment by sirosen** [comment]
:+1: for the idea of giving simpler default output, similar to unix `whoami`.

While we're on the topic, can we do `ID` in caps? `Id:` looks weird, IMO.
