### ISSUE TITLE
Update 'Using the CLI' file transfer example to non-deprecated style

### ISSUE THREAD

**Issue by theroncross** [globus/globus-cli#146]
The transfer command example in the docs (https://docs.globus.org/cli/using-the-cli/#file_transfer) fails with message:

```
$ ssh ****@cli.globusonline.org transfer -- go#ep1:/share/godata/file1.txt go#ep2:~/myfile.txt
Error: Invalid endpoint name 'go#ep1:': Invalid characters
```

I had to play with other commands to find a solution. The ls command returns a deprecation warning when the SCP syntax is used:

```
$ ssh ****@cli.globusonline.org ls go#ep1:/share/godata/
Warning: SCP style (endpoint:path) URLs are deprecated
Warning: Use endpoint/path or endpoint/~/path instead
```

Probably easier to update the docs, but a similar warning message might be ideal.

**Comment by sirosen** [comment]
@theroncross As it's a documentation issue, I'm going to refile this against our doc site repo and close this out.

Note that this is the repository for our [new CLI](http://globus.github.io/globus-cli/), which you may want to try using anyway. It's in open beta,  so docs.globus.org still documents the existing production CLI.

Anyway, thanks for submitting this! The fix should be easy enough for us to put in place.
