### ISSUE TITLE
Docs should live natively on docs.globus.org instead of being linked to

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#148]
This is for when we come fully out of beta.

We currently link to https://globus.github.io/globus-cli/ from https://docs.globus.org/cli/ -- the new CLI documentation would probably replace https://docs.globus.org/cli/ and that would need to be moved to `/hosted-cli` or `/legacy-cli` or something similar.

**Comment by sirosen** [comment]
We're attacking this via the `/adoc` directory, which is being processed into site content. I'm comfortable closing this as "done on this side".
