### ISSUE TITLE
Test suite expansion

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#149]
Conversation topics to get us going:

- [x] do we want to replace basic_tests.sh with a framework like nose (like the sdk) or unittest?
- [ ] what additional nose tests do we need to add?
- [x] for testing methods that are actually supposed to call live services, do we want to use real test tokens, or do we want to fake the SDK, or fake the services, or both? if we use live test tokens, can this be shared with the SDK test expansion in globus/globus-sdk-python#105?
- [ ] expand to AppVeyor testing for Windows? add OS X on Travis?

**Comment by sirosen** [comment]
Note that Click has some tooling and guidance for testing applications:
http://click.pocoo.org/6/testing/

**Comment by sirosen** [comment]
We're okay on this, but we should continue to think about AppVeyor and othersuch. Moving out of 1.0 milestone.

**Comment by sirosen** [comment]
I'm going to close as I think this issue is historical cruft at this point. Obviously we could always add many more valuable tests if we had the person-hours to devote to it.
