### ISSUE TITLE
globus update

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#154]
Currently the instructions for updating the globus cli are:

source "$HOME/.globus-cli-virtualenv/bin/activate"
pip install -U globus-cli
deactivate

Can we add a "globus update" command that does this?  That will make it easier to keep the CLI updated without having to remember this virtualenv magic every time.

**Comment by sirosen** [comment]
I would love to be able to do this, but I'm pretty sure that any naive implementation of this would be inherently unsafe.

Updating the contents of the virtualenv under which the current console script is running is inherently dangerous and not something we really should want to play with.
Plenty of things won't break, but `pkg_resources` could easily break down catastrophically, and we never know when we use library functions how much they're relying on their disk state.
Even if it works today, there is no guarantee that it will work on any given subsequent update.

If we want this, we need to think of a way of doing this that successfully isolates the running update from the invoking python command. I'm unable to think of one at present, but perhaps we'll come up with something.

Some people out on the internet seem comfortable with the idea of `pip.main()` on their own packages, but I think this is a matter of being ignorant of the dangers (or just not caring).

**Comment by sirosen** [comment]
Something that would be 95% effective (which is really all we need, right?) would be to run `pip.main()` within the exitfunc, using `atexit`. 
I should clarify why I'm comfortable with that, but not with a raw `pip.main()` in the middle of a running CLI command.

All of the dangerous conditions for doing `pip.main()` arise from either doing imports or reads via `pkg_resources` *after* `pip.main()` has run.
I would say that it's highly unlikely that anyone would write code which runs an import of a previously unimported module in a registered `atexit` handler, or which uses `pkg_resources` in an `atexit` handler. Allowing for failure in these obscure and unlikely scenarios seems like an okay tradeoff, so long as we leave ourselves a paper-trail of comments from whence we can deduce that this is at least one way that `globus upgrade` could fail.

I think the best approach is to print a warning message before we start, as in:

```shell
$ globus update
You are currently running the Globus CLI, version x.y.z . An upgrade to p.q.r is available.
Would you like to proceed? [Y/n] 

The Globus CLI will now update itself.
In the event that an error occurs or the update is interrupted, we recommend uninstalling and reinstalling the CLI.

...
```
