### ISSUE TITLE
Missing endpoint update functionality

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#161]
"globus endpoint update" is missing functionality, relative to the ssh CLI.  Specifically:

  --disable-verify      Disable checksum verification of transfers to and from the endpoint
  --no-disable-verify   Unset the --disable-verify setting
  --managed-endpoint    Set managed endpoint subscription
  --no-managed-endpoint   Unset the managed endpoint subscription
  --subscription=UUID   Specifies subscription id to use for --managed-endpoint
  --network-use=LEVEL   Set network usage level: normal, minimal, aggressive, or custom
  --max-concurrency=N   
  --preferred-concurrency=N
  --max-parallelism=N   
  --preferred-parallelism=N
  --location=LOCATION   Set location to "latitude,longitude"

**Comment by jaswilli** [comment]
We need to go through this list and figure out which of these things aren't currently supported via the Transfer API and then decide what, if any, enhancements to the API we're going to push on.

A few of these options are covered in some existing issues:

* #63 (`subscription_id`, `network_use`, `location`, `disable-verify / no-disable-verify`
* #134 (`managed-endpoint / no-managed-endpoint`)

**Comment by sirosen** [comment]
IIRC, `--max-concurrency`, `--preferred-concurrency`, `--max-parallelism`, and `--preferred-parallelism` are all missing API support.
I think that they are ignored on update, just like `subscription_id`, but given that the docs don't mention this, it's possible that I'm misremembering.


`--subscription` is a bigger issue because it's a piece of administrative functionality -- even if it was in the hosted CLI, it doesn't really belong in a user-facing tool.
I've floated my thoughts on a [plugin architecture](https://github.com/globus/globus-cli/issues/155) to add functions for privileged users, but I also think this could be done in a less general way, tightly scoped to a special `superuser` plugin. (i.e. detect and load a package if it is present).

**Comment by corpulentcoffee** [comment]
On Wed, Jan 25, 2017 at 7:33 AM, Stephen Rosen <notifications@github.com>
wrote:

> IIRC, --max-concurrency, --preferred-concurrency, --max-parallelism, and
> --preferred-parallelism are all missing API support.
> I think that they are ignored on update, just like subscription_id, but
> given that the docs don't mention this, it's possible that I'm
> misremembering.
>
network_use (along with max_concurrency, max_parallelism,
preferred_concurrency, preferred_parallelism) have API support as long as
the endpoint is managed.

**Comment by tuecke** [comment]
> On Jan 25, 2017, at 8:33 AM, Stephen Rosen <notifications@github.com> wrote:
> 
> IIRC, --max-concurrency, --preferred-concurrency, --max-parallelism, and --preferred-parallelism are all missing API support.
> I think that they are ignored on update, just like subscription_id, but given that the docs don't mention this, it's possible that I'm misremembering.
> 
As Dave said, these work with network-use, if its a managed endpoint.
> --subscription is a bigger issue because it's a piece of administrative functionality -- even if it was in the hosted CLI, it doesn't really belong in a user-facing tool.
> I've floated my thoughts on a plugin architecture <https://github.com/globus/globus-cli/issues/155> to add functions for privileged users, but I also think this could be done in a less general way, tightly scoped to a special superuser plugin. (i.e. detect and load a package if it is present).
> 
—subscription does along with —managed-endpoint.  If I am a subscription manager for multiple subscription, I use the —subscription to specify which subscription I want the managed endpoint to be included in.  It should be supported in the new CLI, assuming the REST API supports it (i.e., it wasn’t a CLI backdoor).

-Steve

**Comment by sirosen** [comment]
If these are available to subscription managers, then I'm definitely wrong and they should be included.
I was under the impression that associating a subscription id required a higher level of access.

There are other parts of the subscription management tooling to which those thoughts apply.

We still need to check whether or not subscription id is supported via the API.
The rest of these should be easy enough, and should be enabled for endpoint creation in addition to update.

**Comment by tuecke** [comment]
Making somebody a subscription manager (associating an identity with a subscription id) is done by our support team through the super command. But once that is done, the endpoint manager then uses these options to make an endpoint managed under a particular subscription.

-Steve

**Comment by sirosen** [comment]
Done except for #134
