### ISSUE TITLE
--quiet option

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#164]
Add a --quiet option to most commands, to suppress all of informational output.   This is useful for scripting.  Example commands to add it to:

logout
config set
config remove
bookmark rename
bookmark delete
endpoint delete

For commands that print requested output to stdout, the --quiet option would suppress all of the informational text, so that only the critical output is printed.  For example:

$ globus endpoint is-activated af7bda53-6d04-11e5-ba46-22000b92c6ec --quiet
https://www.globus.org/app/endpoints/af7bda53-6d04-11e5-ba46-22000b92c6ec/activate
$ echo $?
1
$

**Comment by tuecke** [comment]
This would be useful on "config set" and "config remove" also.

**Comment by sirosen** [comment]
In most of the example cases, there would be no difference between `--quiet` and `> /dev/null`.
I can see this as desirable, but not on the critical path.

**Comment by tuecke** [comment]
On the critical path to what?  There are many items that may or may not be on the critical path, depending on how you define that.  I'm trying to submit everything I run across that I think should be  added or fixes.  If you just means its probably on the lower end of the priority spectrum, I agree.
