### ISSUE TITLE
globus --version vs. globus version

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#165]
It seems odd to me that --version is an option that can be provided to any command.  It just clutters up the help text for every command.

Why is it not just "globus version"?

**Comment by sirosen** [comment]
This is a matter of taste with many, many examples on both sides.

I don't have a strong feeling, but it seems nice to me to be able to append `--version` to a command.
That way, you can do this:
```shell
$ globus blah blah blah
... # maybe something unexpected happens
$ !! --version
```
