### ISSUE TITLE
Two blank line in information messages

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#166]
I notice that at least globus login and globus logout have 2 blank lines in their informational messages.  Why?  Isn't a single blank line a sufficient separator?

**Comment by sirosen** [comment]
:man_shrugging: 

I thought the output was a lot more readable with extra whitespace, and it does no harm.

Is there a particular reason to want to tighten it up?

**Comment by tuecke** [comment]
I have a general preference against extraneous vertical whitespace.  Just ask Vytas.  The underlying reason is probably that I tend to work pretty often on a small screen, to extraneous vertical whitespace can cause me to have to scroll sometime when I shouldn't have to.

**Comment by sirosen** [comment]
I view this as a matter of taste and have no strong feelings.

If this is a consistent design theme for us, let's get it fixed and keep an eye out for it in future tools. Changing the labels around on this one.
