### ISSUE TITLE
whoami: linked identities

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#167]
globus whoami should have an option to see all of my linked identities.  I suggest an additional --linked-identities option that will print out all of the linked identity usernames after the primary identity.  And if combined with --verbose prints the verbose form for each of those linked identities.

**Comment by sirosen** [comment]
There is no API (or at least, no documented API) by which we can fetch this information.
Token introspection is only available to resource servers.

It seems like reasonable added value to offer, if there is a way of getting it.

**Comment by aaschaer** [comment]
Closing as duplicate with #115
