### ISSUE TITLE
get-identities: output only identity id or name

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#172]
get-identities does not appear to have an easy way to get back just the identity id for a username.  For example, what I want is:

$ globus get-identities tuecke@uchicago.edu --xxx
b04b1e76-d274-11e5-bf36-07c9790e3d20

Perhaps --xxx should be "--format short".  Or "--fields identity_id --format csv".  

Likewise 
$ globus get-identities --identities b04b1e76-d274-11e5-bf36-07c9790e3d20 --xxx
tuecke@uchicago.edu

For multi-valued input, have one output per line, the same order as they appear on the command line.  For example:

globus get-identities tuecke@uchicago.edu tuecke@globusid.org --xxx
b04b1e76-d274-11e5-bf36-07c9790e3d20
b0497184-d274-11e5-bf33-130e800f88c2

**Comment by sirosen** [comment]
Rather than mucking about with another textual format definition, I'd suggest making the current output the result of `--verbose` and defaulting to this output type.

That's simple, and consistent with the behavior of `globus ls --long` and `globus whoami --verbose`.

**Comment by aaschaer** [comment]
closing as resolved by #253
