### ISSUE TITLE
`globus -F json` errors, instead of behaving like bare `globus`

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#174]
globus -h lists -F, --format as an option:

$ globus -h
Usage: globus [OPTIONS] COMMAND [ARGS]...

Options:
  --version                 Show the version and exit.
  -h, --help                Show this message and exit.
  -F, --format [json|text]  Output format for stdout. Defaults to text
...

But if I try to use it, I get an error:

$ globus -F json
Usage: globus [OPTIONS] COMMAND [ARGS]...

Error: Missing command.

Do you mean that these options are global options, which can be used pretty much everywhere?  If so, perhaps change the "Options:" header to "Global Options:"

**Comment by sirosen** [comment]
I think the best behavior in this case is for `globus -F <format>` to behave the same way as `globus` without any args and produce the `globus --help` output.

`globus -F json CMD` works fine, and applies the JSON format to the subcommand.

I'm not sure how easy this will be to resolve -- we'll have to look at how `click` handles the "no args means helptext" case and maybe use the same approach.
