### ISSUE TITLE
.globus.cfg: duplicated tokens?

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#175]
What are the transfer and auth tokens duplicated in the [general] and [cli] sections of the ~/.globus.cfg file?

**Comment by sirosen** [comment]
These are an artifact of the transition off of the tokens.globus.org authentication path.
There's a TODO to remove them, blocked on globus/globus-sdk-python#126

**Comment by jaswilli** [comment]
Closed by https://github.com/globus/globus-sdk-python/pull/126
