### ISSUE TITLE
login: auto-fill consent label with hostname

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#176]
When running "globus login", on the Globus Auth consent screen it should auto-fill the "Provide a label for future reference" with the hostname.

**Comment by sirosen** [comment]
Is there an Auth option for this?

I recall asking for one in the past, but there's nothing in https://docs.globus.org/api/auth/ to suggest that it was ever implemented.
As soon as docs go up, we should add SDK support and leverage it here.

**Comment by mattias-lidman** [comment]
I believe the `prefill_named_grant` param would accomplish this.
