### ISSUE TITLE
config help

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#177]
The only way I could figure out what the various "config" commands do was to play with it.  The help text wasn't much help.

The "globus config -h" text should probably say that the config file is used to store various config parameters such as access tokens automatically, but that there are some config options that the user can set to configure the default behavior of the CLI.  Then list those user-definable options (e.g., cli.output_format).

It was not clear from the "config init" help that it would interactively prompt me to set user-definable configuration values, namely for output_format.  But is the "config init" even needed?  It seems redundant with "config set", aside from its interactive nature.  But I suppose if there are more user-definable options, that would be useful.

Perhaps have a common example that you use across all of the config help messages.  For example, in "config set" show how to set cli.output_text to json.  In "config remove", show how to remove the cli.output_text.  In "config show", show how to show the cli.output_text.

**Comment by sirosen** [comment]
We haven't paid much attention to these commands as it's not clear whether or not we should keep them.
There's a case to be made that even the `output_format` option isn't necessary, and no other config parameters have been added or surfaced as desirable.

I'll put this and the other `globus config` issues into the `1.0` milestone, but we should take a moment to discuss the future of these commands.

---

> It was not clear from the "config init" help that it would interactively prompt me to set user-definable configuration values, namely for output_format. But is the "config init" even needed? It seems redundant with "config set", aside from its interactive nature. But I suppose if there are more user-definable options, that would be useful.

My desire for that command was based on my own experience with `knife`. The `knife init` command is more or less essential, as there are six or seven options which you must set to even get started with the tool, and without the interactive prompts I can't imagine doing it correctly every time.

The same rules may not apply to us; I'm not sure.

**Comment by sirosen** [comment]
@aaschaer, I'd like you take point on this, since we've had no new insights and we're short on time.

Let's remove `globus config edit`, and try to improve docs on the rest.

I think these commands should say, in their helptext, that they are for advanced users only.
We'll hold off on really changing them significantly for now.

**Comment by aaschaer** [comment]
Sounds good.
