### ISSUE TITLE
get-identities: remove --usernames & --identities

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#179]
Why does "globus get-identities" need the --usernames and --identities options?  They have unambiguous syntax.  A username is always user@domain, and an identity id is always a UUID.  The CLI should just figure that out, and not make me add the option.

Note that "globus bookmark show" does essentially the same thing, allowing me to input either a bookmark name or id, but it does not require me to include an option to say which I am inputting.

**Comment by sirosen** [comment]
This is an artifact of this being one of the oldest commands and it hasn't seen much love.

I think it should also accept a mixed list of inputs.
We'll no longer be able to pass things verbatim to the API -- we need to split the list into categories and potentially make two calls to produce output.

Output formatting may be slightly tricky, as we'll no longer have a single response to feed to the formatting code. Assembling a synthetic response might be best.
