### ISSUE TITLE
ls: file globbing

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#192]
The ssh CLI supports shell-style globbing.  Do "man glob" in the ssh CLI for information.  For example:

$ ls af7bda53-6d04-11e5-ba46-22000b92c6ec/~/myproject/exp*
experiment1/
experiment2/
experiment3/

The new CLI should offer similar support.  It should do:

$ globus ls 'af7bda53-6d04-11e5-ba46-22000b92c6ec/~/myproject/exp*'
experiment1/
experiment2/
experiment3/

**Comment by sirosen** [comment]
We would want the behavior of this to be consistent with the `globus delete` interpretation of globs, but it's not clear that the `filter` parameter on `ls` supports the same patterns.
Needs investigation.

**Comment by aaschaer** [comment]
After some investigation while working on `globus rm`, it seems that the filter parameter for ls supports using `*` and `?` globbing, but not `[ ]`, whereas delete task globbing supports all three. 

It seems very confusing to users if
`globus rm` (and `globus delete` if we want?) accepts `*` `?` and `[ ]`
`globus ls` accepts `*` and `?` but *not* `[ ]`
and `globus transfer` can't use globbing at all.

Are good docs enough for this, or should we wait for the API to make it possible to be consistent with our globs accross the board?

**Comment by tuecke** [comment]
I think just doc  its behavior at this point. We have on our backlog to add much richer, server-side globbing/ expression support, but probably not until later this year.

-Steve

**Comment by corpulentcoffee** [comment]
Closed by #384
