### ISSUE TITLE
ls -h confusing:   --recursive-depth-limit INTEGER RANGE

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#194]
The help message for --recursive-depth-limit is confusing:

  --recursive-depth-limit INTEGER RANGE
                                  Limit to number of directories to traverse
                                  in `--recursive` listings. A value of 0
                                  indicates that this should behave like a
                                  non-recursive `ls`  [default: 3]

Does this option take one parameter or two?  I think just one, but "INTEGER" space "RANGE" suggests 2.

**Comment by sirosen** [comment]
`INTEGER RANGE` is the default metavar for `click.IntRange`.
We should just set a custom metavar as `INTEGER` on the option.
