### ISSUE TITLE
ls: orderby

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#195]
The REST API for ls supports an orderby query param: https://docs.globus.org/api/transfer/file_operations/#dir_listing_query_parameters

We should expose that functionality through the CLI.

**Comment by sirosen** [comment]
I'm not sure how this applies in the `--recursive` case. Needs dicussion.

**Comment by sirosen** [comment]
I was considering closing this (but for various reasons don't want to do so).
I don't recall exactly what happened with #290, but it looks like we decided against it -- maybe in the pursuit of simpler and more maintainable code.

If we want to revisit, I think the right thing would be to make `--orderby` mutex with `--recursive`.

**Comment by sirosen** [comment]
This has moved to internal issue tracking. I'm also trying to reprioritize this, since it should be relatively easy if someone takes the time to focus on it.
