### ISSUE TITLE
transfer -h is too long

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#198]
The "globus transfer -h" help message is too long.  -h should give short help, not the long documentation that is there.  Perhaps we need a standard long-form help in the CLI. The ssh CLI has "man command" for every command that has a man-page like manual. Perhaps have a similar "--man" option for every command that prints out man-page like documentation.

**Comment by sirosen** [comment]
I agree wholeheartedly, and we do have #6 as an outstanding TODO.
I experimented with having `--man` on the `transfer` command specifically, and I think it worked pretty well.

However, I've also heard the opinion that long-form help could just be served off of the docs site, and we could add a link to the `--help` output.

Reformatting helptext into a manpage automagically doesn't work very well, and avoiding redundant docs requires that we pull manpage details directly out of the command structure.
My experiments doing this were actually pretty successful, and we could generate docs to render (rst or asciidoc, whatever it may be) or a manpage using that approach.
