### ISSUE TITLE
transfer --batch: -r at beginning or end

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#199]
The ssh CLI puts the -r at the end of a batch input line to denote recursive.  The new CLI puts --recursive at the beginning -- at least, that is what the example in the help text shows.  Can it optionally go at the end also?  Ideally it would, so that people migrating from the old CLI don't trip over that small detail.

**Comment by sirosen** [comment]
Each line of batch input is processed as its own command line, kind of like it's being fed to a "micro CLI" which only understands two arguments and the `--recursive` flag.

As a result, `--recursive` can go anywhere in the command line.

Allowing `-r` as a short flag for `--recursive` falls into a larger debate about how we approach short-flags.
I'm going to close this, but if we switch non-batch tasks to accept `-r` we'll need to do it to the `--batch` mode as well.
