### ISSUE TITLE
transfer --sync-level: change option name to --sync and -s

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#201]
The "level" in "sync-level" does not make much sense with textual sync levels, instead of numeric sync levels.  I suggest change it to just "--sync", with a "-s" alias.

**Comment by sirosen** [comment]
We should talk about this a little. I think `--sync-level checksum` checks out pretty well.
`--sync` sounds like a boolean flag option (i.e. "sync on" vs. "sync off").

I'm also wary of adding short form options too aggressively. They tend to make commands highly inscrutable, and are almost always harder to remember than their long-form counterparts.
Case in point: BSD `cp -R` vs. GNU `cp -r` vs. our `--recursive` flag.

**Comment by sirosen** [comment]
Confirmed a while back that we're keeping `--sync-level` as the long name. Closing.
