### ISSUE TITLE
delete -r -f: add short forms

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#204]
add -r as alias for --recursive
add -f as alias for --ignore-missing

**Comment by sirosen** [comment]
I'm fine with `-r` as a shorthand for `--recursive`, but `-f/--ignore-missing` seems like a very odd combination.

`-f` is often the short form of `--force`, which can mean all kinds of things. `rm -f` has quite different meaning from `globus delete --ignore-missing`, and I worry the mismatch could produce confusion.
(Yes, `man rm` makes it sound like `-f` skips missing files as its primary function, but skipping prompts is actually hugely important.)
The most comparable option on a well-known command is probably `--ignore-existing` on `rsync`, which has no short-form.

We can do it, but I want us to make sure that's actually the right behavior.
