### ISSUE TITLE
globus transfer --batch: accept filename

### ISSUE THREAD

**Issue by tuecke** [globus/globus-cli#222]
Currently globus transfer --batch is defined to take the list of input files on stdin.  Rather than forcing stdin, why not define it as "--batch INPUTFILE", where INPUTFILE can be "-" to mean stdin?  That seems somewhat more flexible and easier, if my file list is in a file.

**Comment by sirosen** [comment]
I think this would be a good change, but a compatibility-breaking one.
Labeled for v2.
