### ISSUE TITLE
Investigate moving off `six`, along with SDK

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#26]
Per globus/globus-sdk-python#51 , we're trying to get off of the dependency on `six` because OSX makes things difficult.
This is largely matter of supporting the naive developers who don't realize that there's a strong reason to use virtualenv.

At present, we're using

- `six.string_types` (easy to sub with some version dispatch)
- `six.reraise`

The `reraise` functionality is hard to imitate, so we'll need to take another look at where and how that's happening. I don't think we can do the current exception handling logic without a `reraise`, but maybe we don't need to preserve context (I think that's just paranoia about how `click` might behave).

**Comment by corpulentcoffee** [comment]
The `reraise` implementation in Six is a [little gross](https://bitbucket.org/gutworth/six/src/ca4580a5a648fc75abc568907e81abc80b05d58c/six.py?at=default&fileviewer=file-view-default#six.py-680), I guess because the Python 2.7-style `raise x, y, z` syntax won't even parse under Python 3 (i.e. it is an uncatchable `SyntaxError` there).

**Comment by sirosen** [comment]
@jaswilli @corpulentcoffee I think we need to reopen this discussion.

Karl found that a global install fails on Ubuntu 14.04 because the Debian package `python-six` ships with v1.5.6
That package is depended upon by a bunch of other Ubuntu packages, and it's all a sticky ball of mud.

Can we consider what it would be like if we wrote with `six>=1.4.1,<2.0.0`?
I know we'd have to handle the ConfigParser location change ourselves, but I think that's it.

I'm also okay with just putting six in tree (in the SDK), since it has no dependencies. However, I think that's actually significantly more work than just expanding the set of versions we support.
We already cast a pretty wide net on `requests` because people are likely to have that installed and we don't need any advanced features, so this would be "consistent" with that, FWIW.

**Comment by bjmc** [comment]
You could look at https://pypi.python.org/pypi/future as an alternative to six.

**Comment by corpulentcoffee** [comment]
Closed by globus/globus-cli#41
