### ISSUE TITLE
Add some way of protecting the refresh token / not storing it as plaintext?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#287]
I was asked about this at GlobusWorld, and, while we probably don't want to tackle this today, we should record the request/thought. There are several variants of this.

One option is for us to say that "You should encrypt your homedir, or link `~/.globus.cfg` to a file in an encrypted dir". That works today, but it presumes

- that the user is comfortable working with dir encryption of some kind
- that the user is okay with the refresh token being protected, for the case of homedir encryption, only from attackers who do not have any ability to act as the user (vs. a malicious program)

In terms of actual solutions, there are many variants, but some options as food for thought:

- password-protect using `globus lock` and `globus unlock` commands
- allow the user to set or pass (to any command) an encryption keyfile, which is used to encrypt/decrypt auth data
  Users are free to manage the keyfile however they like
- allow `globus login --ephemeral` which _does not_ request refresh tokens, and says its for short-term use only
- let the user provide (command-line or config) a `secret_decrypt_hook` and `secret_encrypt_hook` which is a command to run in subprocess; perhaps with special value "openssl" which we know means to "do the right thing" with the openssl commandline tool and a password

**Comment by mattias-lidman** [comment]
I think the problem with each of these is that a user that doesn't know to store credentials in an encrypted (home) directory won't see the point of (or at least won't go looking for) these solutions. Unless you're suggesting making one of these the default.

**Comment by sirosen** [comment]
Yes, 100% agree. But it's also maybe about having a good answer when someone incredulously asks, "You store it in plaintext?!"
I'm not invested in really doing this.

**Comment by jaswilli** [comment]
There's always just `globus logout` when you're done, if you're concerned.

Also, this: https://github.com/jaraco/keyring seems like it could be a possible technical solution, should we ever want to venture down this road.

**Comment by sirosen** [comment]
I think we should close this so that it's clear we don't plan on doing it.
We can reopen if it ever becomes necessary.
