### ISSUE TITLE
Add help text about detailed help

### ISSUE THREAD

**Issue by rpwagner** [globus/globus-cli#298]
The detailed help is great, but there's no way I can find on the command line to figure out that it's there. Likewise, my limited exploration didn't show me suggest add a line like the following to the general help text.

```
globus COMMAND --help    Gives more detailed help on COMMAND
```

P.S. Another way to tackle this would be through create a new command, `help`, which fits the mostly verb-based model of the CLI. Then a detailed help command would be:

```
globus help COMMAND    Gives more detailed help on COMMAND
```

Like

```
$ globus help transfer

Usage: globus transfer [OPTIONS] SOURCE_ENDPOINT_ID[:SOURCE_PATH]
                       DEST_ENDPOINT_ID[:DEST_PATH]

  Copy a file or directory from one endpoint to another as an asynchronous
  task.

  Batched Input
  ===

  If you use `SOURCE_PATH` and `DEST_PATH` without the `--batch` flag, you
  will submit a single-file or single-directory transfer task. This has
  behavior similar to `cp` and `cp -r`, across endpoints of course.

  Using `--batch`, `globus transfer` can submit a task which transfers
  multiple files or directories. Paths to transfer are taken from stdin.
...
```

**Comment by sirosen** [comment]
I don't think that this is a problem. Even accepting the precept that it is one, I wouldn't consider it something which we can or should attempt to resolve.

If a user is insufficiently familiar with CLI tools to try `--help`, there's not very much that we can do to be instructive.
This is a very standard way for tools to self-describe, and anything different or non-standard would just be more confusing.

Closing as a wontfix. Hope this explanation has been `--help`ful.

**Comment by rpwagner** [comment]
@sirosen, because I may have fumbled my description at the beginning, I'll restate what I wanted to get across. There's no way that I can find for the user to know that `globus COMMAND --help` exists. And the usage line from `--help` implies that it would be `globus --help COMMAND`. Hence my suggestion of adding 
```
globus COMMAND --help    Gives more detailed help on COMMAND
```
to the help output so that users know that the detailed help is there. The postscript about adding `globus help COMMAND` was just a sidebar.

No need to reopen this.

Current help output below.

```
Magik:~ rpwagner$ globus --help
Usage: globus [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose             Control level of output
  -h, --help                Show this message and exit.
  -F, --format [json|text]  Output format for stdout. Defaults to text
  --jmespath, --jq TEXT     A JMESPath expression to apply to json output.
                            Takes precedence over any specified '--format' and
                            forces the format to be json processed by this
                            expression
  --map-http-status TEXT    Map HTTP statuses to any of these exit codes:
                            0,1,50-99. e.g. "404=50,403=51"

Commands:
  bookmark        Manage endpoint bookmarks
  config          Manage your Globus config file. (Advanced Users)
  delete          Submit a delete task
  endpoint        Manage Globus endpoint definitions
  get-identities  Lookup Globus Auth Identities
  list-commands   List all CLI Commands
  login           Login to Globus to get credentials for the Globus CLI
  logout          Logout of the Globus CLI
  ls              List endpoint directory contents
  mkdir           Make a directory on an endpoint
  rename          Rename a file or directory on an endpoint
  task            Manage asynchronous tasks
  transfer        Submit a transfer task
  update          Update the Globus CLI to its latest version
  version         Show the version and exit
  whoami          Show the currently logged-in identity.
```
