### ISSUE TITLE
globus task show missing output fields

### ISSUE THREAD

**Issue by ranantha** [globus/globus-cli#300]
Per document, https://docs.globus.org/cli/reference/task_show/, this command should display more details on the task. But currently I see a limited set.  @ianfoster reported this and notes that this is blocker when managing multiple transfers.

[ranantha@eduroam062-090:~] globus task show 8bf24714-2f63-11e7-bca3-22000b9a448b
Label:                None
Task ID:              8bf24714-2f63-11e7-bca3-22000b9a448b
Type:                 TRANSFER
Directories:          0
Files:                2
Status:               SUCCEEDED
Request Time:         2017-05-02 18:17:06+00:00
Completion Time:      2017-05-02 18:17:10+00:00
Source Endpoint:      UChicago RCC Midway
Destination Endpoint: Globus Tutorial Endpoint 1

**Comment by aaschaer** [comment]
Currently the set is limited to fields "which apply"

All tasks have Label, Task ID, Type, Directories, Files, Status, and Request Time
Active tasks will have Deadline and Details
Completed tasks will have Completion Time
Delete tasks have Endpoint
Transfer tasks have Source Endpoint and Destination Endpoint

Should all fields be displayed regardless of task status/type, or should we just be more clear about which fields "apply" in the docs?

**Comment by ranantha** [comment]
I meant to put in a reference to the hosted CLI details document, https://docs.globus.org/cli/hosted/details/. byte_transferred there is one noted as something that is missing in the new CLI.
