### ISSUE TITLE
Full details -t parity for task show

### ISSUE THREAD

**Issue by aaschaer** [globus/globus-cli#302]
Currently task show -t is only partially equivalent to details -t, as the 	
/task/<task_id>/successful_transfers resource only gives information about transfers, and is missing code, faults, and subtask_id fields.

Blocked on API support for delete subtasks and missing fields.

**Comment by jaswilli** [comment]
Did this come as a request from someone? Way back when Karl said when this was implemented in the new CLI that it should use `/successful_transfers`.

**Comment by aaschaer** [comment]
Not exactly, it came up when working on #300 at @ranantha's request, and I wasn't able to get all the fields for details -t.

Since we have that nice disclaimer about -t not being guaranteed to be backwards compatible this can probably be closed as a non issue if Karl said to do otherwise.
