### ISSUE TITLE
`globus login` incorrectly captures KeyboardInterrupt in fancy browser mode

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#319]
Easy to reproduce:

1. `globus login` to start the login flow with the browser interactivity.
2. Go back to the shell where `globus login` is running
3. Ctrl+C

Nothing happens.
The login command should die upon receipt of an interrupt.

I can workaround this by `Ctrl+Z; jobs; kill %n`, but that's silly.

**Comment by jaswilli** [comment]
As discussed, this is a known issue and one that's not simple to work around.

I think we should decide if someone is going to do the work to fix it, and if not, just close this issue instead of letting it languish.

**Comment by sirosen** [comment]
> I think we should decide if someone is going to do the work to fix it, and if not, just close this issue instead of letting it languish.

Well, obviously since it bothers me and I'm super-picky about this kind of stuff, I'm going to keep trying to fix it until I get something to work. :smile: 

I'm also not sure I agree. Even if we weren't going to work on it, I'd want to have it open in tracking as a known defect.

**Comment by jaswilli** [comment]
Only if we're going to fix it though. Otherwise we can close the issue and it'll show up in the search results documentation purposes.
