### ISSUE TITLE
Creating an endpoint ACL/role or doing an endpoint search by owner using an identity username that doesn't exist in Auth yet raises an IndexError

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#326]
If a CLI user tries `globus endpoint role create --identity`, `globus endpoint permission create --identity`, or `globus endpoint search --filter-owner-id` and they supply a username that doesn't exist in Auth yet, `_lookup_identity_field()` will raise an `IndexError` when calling `client.get_identities()` because the `provision=True` flag isn't passed to the SDK.

I think that probably

- CLI codebase callers of `maybe_lookup_identity_id()` need to indicate whether to provision
- `endpoint endpoint search` shouldn't provision
- `endpoint endpoint permission` and `globus endpoint role` should either provision *or* expose a flag for the CLI user to indicate that they want to provision an identity should the one that they passed not exist

**Comment by sirosen** [comment]
> - CLI codebase callers of `maybe_lookup_identity_id()` need to indicate whether to provision
> - `endpoint endpoint search` shouldn't provision

Agree with these.

> - `endpoint endpoint permission` and `globus endpoint role` should either provision *or* expose a flag for the CLI user to indicate that they want to provision an identity should the one that they passed not exist

I think that they _should not_ provision by default, and should instead error. As we've often discussed,
`schiflet@globusid.org` shouldn't be accepted in lieu of `shifflett@globusid.org`.

If you're going to provision a new ID, you should always be doing so knowingly.

Another option is to make this be an error, and require provisioning is done by passing a flag to `globus get-identities`.
I'm not sure if that's much worse than adding a flag to these commands, and it seems like it might be a little bit cleaner?
Between that and a new flag, it seems like a tossup.

**Comment by jaswilli** [comment]
I opened #327 as a WIP so that we can play with the actual behavior while figuring out if/how we handle the auto-provisioning.
