### ISSUE TITLE
Error when roles or permission list contains an entry that has a non-existent identity

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#328]
`globus endpoint role list <uuid>` and `globus endpoint permission list <uuid>` assume that every entry in the list will resolve to an identity so the `username` can be printed. However, Transfer allows ACLs and roles to be assigned to arbitrary UUIDs.

Example:
![screen shot 2017-06-19 at 9 31 05 am](https://user-images.githubusercontent.com/214142/27290162-0212f46e-54d2-11e7-831e-2a6d809ff7ca.png)

CLI output:
```
globus endpoint role list 78ff1934-4638-11e7-bd4f-22000b9a448b
IndexError: list index out of range
```

Will fix as part of #327.

**Comment by sirosen** [comment]
Should we also file a Transfer bug regarding this? Trying to assign an ACL to an ID which doesn't resolve should probably be an error.
Or are we aware of an obscure use-case for this behavior?

**Comment by mattias-lidman** [comment]
> Or are we aware of an obscure use-case for this behavior?

In a future world where the Identities API is distinct from token validation in Auth, such that the Identities API can be down while token validation still works, maybe.

I can't think of a real use-case.
