### ISSUE TITLE
Help text for endpoint update is ambiguous

### ISSUE THREAD

**Issue by vasv** [globus/globus-cli#339]
The  help text for ```globus endpoint update``` says:

<pre>
--subscription-id UUID            Set the endpoint as a managed endpoint with
                                  the given subscription ID. Mutually
                                  exclusive with --managed/--no-managed.
--managed / --no-managed          (Un)set the endpoint as a managed endpoint.
                                  Requires the user to be a subscription
                                  manager. If the user has multiple
                                  subscription IDs, --subscription-id must be
                                  used instead of --managed to specify one.
</pre>
It should break out the ```--no-managed``` option separately since, for those users with multiple subscription IDs, you cannot specify a subscription ID if you want to unset the managed flag on an endpoint.

**Comment by sirosen** [comment]
To clarify, you'd prefer the following?
```
--subscription-id UUID            Set the endpoint as a managed endpoint with
                                  the given subscription ID. Mutually
                                  exclusive with --no-managed.
--managed                         Set the endpoint as a managed endpoint.
                                  Requires the user to be a subscription
                                  manager. If the user has multiple
                                  subscription IDs, --subscription-id must be
                                  used instead. Mutually exclusive with
                                  --no-managed.
--no-managed                      Unset the endpoint as a managed endpoint.
                                  Requires the user to be a subscription
                                  manager. Mutually exclusive with
                                  --managed/--subscription-id.
```

We can support that change, or something similar.
Before updating, can you confirm that the above text looks good to you? Is there a clearer alternative which works for this purpose? This also lets us subtly hint at the fact that you can pass `--managed` and `--subscription-id` together (not that it does anything other than `--subscription-id` on its own).

(Note on internals: this will require an extra param declaration on each of `--managed` and `--no-managed` as separate flags, and explicitly setting `flag_value` for each.)

**Comment by vasv** [comment]
That looks fine as you propose.

**Comment by corpulentcoffee** [comment]
> `--no-managed Unset the endpoint as a managed endpoint. Requires the user to be a subscription manager. ...`

It's actually not required to be a subscription manager to set a `subscription_id` on an endpoint to `null` as long as you're an endpoint administrator.

**Comment by jaswilli** [comment]
Yes, this is true. While testing this command I did a lot of `--no-managed` calls on an endpoint with an account that wasn't a subscription manager.
