### ISSUE TITLE
Expand adoc description of batch transfer mode + `--recursive` flag

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#341]
This relates a little to globusonline/docs.globus.org#180

Someone mentioned in a ticket that he found the "Using the CLI" doc inconsistent with the reference.
If my guess is right, this is because we're not sufficiently clear in the reference documentation that command-line `--recursive` and batch-mode `--recursive` are different and mutually exclusive.

We may want to further clarify with a one or two examples on the reference page, as in
```shell
$ globus transfer --batch ...
xyz def
--recursive a b
c d --recursive
```

**Comment by aaschaer** [comment]
Upon starting to clarify this behavior in the adoc I realized that a similar clarification for the `--symlink` option is  also needed, so I'm now clarifying both in #343

**Comment by corpulentcoffee** [comment]
Closing this per #379.
