### ISSUE TITLE
Grant public read privileges to a sub folder on a shared endpoint

### ISSUE THREAD

**Issue by achourasia** [globus/globus-cli#346]
Is it possible to grant public read privileges to a sub folder on a shared endpoint using cli?

I can share using the following command with a designated user, but  how can I make a folder public
```
globus endpoint permission create --permissions r "$my_endpoint:/$share_folder/" \
                                        --provision-identity $sharee_email
```

**Comment by sirosen** [comment]
Hi @achourasia, sorry it took so long to reply.
Yes, it is possible.

You should be able to use `globus endpoint permission create --anonymous` or `globus endpoint permission create --all-authenticated`.
Details on the distinction (and all the available behaviors) are available via `globus endpoint permission create --help`.

**Comment by achourasia** [comment]
Great thanks
