### ISSUE TITLE
Keep shared endpoint activated indefinitely

### ISSUE THREAD

**Issue by achourasia** [globus/globus-cli#348]
Is it possible to keep a shared endpoint activated indefinitely, if so how?

**Comment by sirosen** [comment]
Questions (as opposed to feature requests and bug reports) don't really belong in GitHub issues.
You could ask this at developer-discuss@globus.org or support@globus.org

However, to answer your question: [Shared Endpoints use Autoactivation](https://docs.globus.org/api/transfer/endpoint_activation/#auto_activation), and therefore _are_ activated indefinitely.
