### ISSUE TITLE
Check if user has authenticated before attempting authenticated calls

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#37]
This is a bit of an open question.

Right now, if you attempt an authenticated action like `globus transfer ls ...`, you get a 401 error back.
Ideally, for any call that cannot be made unauthenticated, the relevant commands would give you a "no auth" error of some kind and direct you to `globus login`.

The big question here is where and how this gets enforced.
Some calls are available unauthenticated, but I'm not sure that it's worth extra burden to support that mode of usage.
If all calls which talk to the service are forced to be made with credentials, then the problem is solved neatly and easily.
However, if we do want to support this case, then we need to figure out where credentials are and are not required.

When HTTPS endpoints enter the ecosystem with possible "public read" ACLs, the desire for unauthenticated calls to be supported _may_ (not necessarily _will_) increase.

**Comment by aaschaer** [comment]
Was #299 sufficient to close this?
