### ISSUE TITLE
Globus Connect Personal UUID

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#371]
GCP has a file containing the UUID of its endpoint. Unix installs it goes in `~/.globusonline/lta/client-id.txt` and on Windows it goes in `%LocalAppData%\Globus Connect\client-id.txt`.

So we do have the ability to provide a command to show the UUID to a user which I think we certainly want to do.  The question is really, should this just be implemented directly in the CLI or should we also add SDK methods?

**Comment by sirosen** [comment]
I like the idea of it being in the SDK. Can we pursue that as our "first choice" solution?

There are questions about how to expose this / name it in each product.

If it's added to the SDK, does this before part of some `LocalGlobusConnectPersonal` controller class? It would have any extra methods *yet*.
We definitely want to add it to the CLI, but what's a good command name? I think I had suggestions in our meeting notes, will look them up.
