### ISSUE TITLE
Make API maintenance mode a prettier error

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#372]
APIs may return 503s when down for scheduled maintenance.
In an ideal world, this would render as a pretty error (but still an error).

**Comment by rohder** [comment]
This came as feedback from user Galen Arnold - support ticket https://globusonline.zendesk.com/agent/tickets/308916

**Comment by sirosen** [comment]
The original bug report that led me to open this issue was actually an SDK bug, not a CLI bug.
As such, I'm not sure there's any pressing need for the CLI to gracefully handle 503s with messages and potential Retry-After headers.

The current error handling seems satisfactory.
