### ISSUE TITLE
Add `globus logout` command

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#38]
The inverse of `globus login`.
This can't touch the consent in Globus Auth, but it should invalidate all of your tokens by revoking them, and scrub them from the config file.

**Comment by bjmc** [comment]
That seems reasonable to me. Arguably it should supply a link to the Auth logout page, but that doesn't seem necessary to me. In the context of a CLI app, "logout" would be logging out of that app, not logging my browser out of the Auth site.

**Comment by mattias-lidman** [comment]
A CLI user may not even be logged into the Auth website in the first place. But maybe it should also print something to the effect of `Go to https://auth.globus.org/consents if you want to _really_ end whatever you were up to`.

**Comment by sirosen** [comment]
> A CLI user may not even be logged into the Auth website in the first place.

I assume that you mean that their session might be long gone if it's been a long time since they consented?
They'll have to sign in via the Native App flow, and maybe want to kill their various sessions.

Having a pointer into the consents page is okay for now. Do we have a roadmapped feature to revoke a consent via an API call?
I could see us also rendering a consent inert / removing it if all tokens issued under it are revoked.
It would be nice if we could clear out that consent without the user having to dig through the list of 40 consents they created while testing a prototype CLI login ("I'm asking for a friend"...).

**Comment by mattias-lidman** [comment]
> I assume that you mean that their session might be long gone if it's been a long time since they consented?

Right.

> Having a pointer into the consents page is okay for now. Do we have a roadmapped feature to revoke a consent via an API call?

No, I think consent management is something we'll want to keep entirely within the Auth website.

> I could see us also rendering a consent inert / removing it if all tokens issued under it are revoked.
It would be nice if we could clear out that consent without the user having to dig through the list of 40 consents they created while testing a prototype CLI login ("I'm asking for a friend"...).

I think it would lead to a confusing user experience (for users less prolific than your friend) if consents magically disappeared. But I guess even fairly normal users might eventually end up with a whole bunch of dead-in-the-water consents. May highlight them on the page and provide a "Cleanse!" button?

**Comment by sirosen** [comment]
I think that would work, as it avoids the "many dead CLI consents" that people are likely to see if they run `globus login` repeatedly.
Another option is auto-scrolling to the CLI consents. Maybe that could be done with the current `client_id` param?

If you send the average user into that view, they won't know what they're looking at and will likely say "Oh, I guess I shouldn't mess with this stuff."
That's a pretty sane fear-response, so we need to coach them through it if we want anyone to use the feature.


I'll open a feature request against auth for the relevant behaviors. Depending on how messy it looks Auth-side, the CLI might just punt and give the consents link with its client ID in the hope that it will "mean the right thing".

**Comment by jaswilli** [comment]
Since #112, we're storing identity information in the config file, so `globus logout` should also clear that data out of the config.
