### ISSUE TITLE
Make shell completion supported, change recommended sourcing method

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#386]
cc @ranantha, I'd like us to make the current completion support an officially supported part of the CLI for GlobusWorld. I think that would be a nice time to add it in; it's a bit of a showy feature which has been done for a while and therefore requires basically no additional work.

The code has been sitting almost entirely untouched (and working) for over a year.
I've been using the current shell completion code for a while now and haven't had any issues with it. It works really well, especially in ZSH where the completion support is a bit superior.

A lot of tools use a nice trick for getting their shell completion stuff into people's bashrc:
`mytool --completion` prints the completer, and users are told to `eval "$(mytool --completion)"`

I like this. Could we add it, maybe move shell completion into the packaged CLI source dir?
We could then document this as a full feature of the CLI.

One thing that we'd need to add, I think, is some way to determine which shell to use. I think `bash` is a sane default, so:
`globus --completion` can do bash completion, and
`globus --completion zsh` can do `zsh` completion

@corpulentcoffee, @jaswilli, I know you guys have been less keen on shell completion than I. Does the change I'm suggesting (putting the current completion scripts into a hidden `--completion` option and documenting it) sound acceptable?

**Comment by corpulentcoffee** [comment]
I don't have any objections to that plan, although I haven't been using the completion functionality myself, so I cannot personally judge its production readiness.
