### ISSUE TITLE
Decide on whether or not to use positional arguments for commands with (at present) required options

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#39]
This is a discussion that we've had on and off pretty much since day one.
When we originally started work on this project, I imitated the awscli's decision to do required options without giving much consideration to whether or not that's correct.

`awscli` is a good model for us to follow because (1) Amazon has many services, we are looking at supporting several services of our own, (2) Amazon employs at least as many Smart People as we do, probably more, and (3) we have experience using this CLI in administrative contexts and can vouch for the cohesion in its design.

However, this _particular_ design decision may not sit well with our CLI, so we should evaluate it within our own context. I have my own bias, but will try to enumerate all of the arguments that I'm aware of.

Favoring Positional Arguments:
- Shorter commands / easier to type
- Clear and well-understood signal of what is and is not required
- Using meaningful ordering (e.x. `SourceID SourcePath DestID DestPath`) maintains readability
- Follows example of `git`, traditional UNIX toolchain (no other known modern tools)

I don't mean to denigrate that first point. It's a matter of good interactive "ergonomics", as we're fond of calling it, and it is important.

Favoring Required Options:
- Reads unambiguously for those unfamiliar with CLI commands
- Separates (visually, not programmatically) "command name" from "arguments and options"
- Can replace required options with config file loads in some cases, as in `aws --region ...` and the `region` config opt
- Follows example of `awscli`, `knife-ec2`, no other known tools

**Comment by sirosen** [comment]
Something that we discussed (without deciding whether or not it's a good idea) is using the config file as a temporary storage solution between runs of commands.
We could also do this with a file in `/tmp/` if that feels cleaner.

That lets us add a feature for storing and retrieving values, which can substitute themselves for repetitive or often-used options.
We can use a syntax similar to the `globus config set` syntax to handle specification.

Consider the case of `globus transfer ls`:

Without tooling, it's
```shell
globus transfer ls --endpoint-id 'aabbccdd' --path '/x/'
globus transfer ls --endpoint-id 'aabbccdd' --path '/x/y/'
globus transfer ls --endpoint-id 'aabbccdd' --path '/x/y/z'
```

But it could be
```shell
globus set transfer.endpoint-id 'aabbccdd'
globus transfer ls --path '/x/'
globus transfer ls --path '/x/y/'
globus transfer ls --path '/x/y/z'
```

Or we can do this where `--endpoint-id` is optional, but `--path` is converted into a positional:
```shell
globus transfer ls --endpoint-id 'aabbccdd' '/x/y/z'
```
becomes
```shell
globus set transfer.endpoint-id 'aabbccdd'
globus transfer ls '/x/y/z'
```

And we also have
```shell
$ globus clear
$ globus transfer ls '/x/y/z'
Usage Error: "globus transfer ls" requires "--endpoint-id"
```

This feature appeals extremely strongly to me, adding `globus set`, `globus show`, and `globus clear` as our three commands.
For `ls` in particular, the notion of setting an endpoint to operate on is much more comfortable than repeatedly specifying it -- positionally or as an option.

Importantly, the semantics only remain clear if the values being set via `globus set` are options.
Otherwise, the command `globus transfer ls aabbccdd` doesn't parse unambiguously.

**Comment by sirosen** [comment]
@corpulentcoffee @jaswilli Do we feel comfortable closing this out, in light of the `EndpointPlusPath` type discussion?

**Comment by corpulentcoffee** [comment]
We have #73 for that, but do we have another (broader) issue for fixing all the other commands that have nothing to do with endpoints?

**Comment by sirosen** [comment]
We do not. I don't think we'll forget the scars of the Required Options / Positional Parameters Seven Months War anytime soon though?

**Comment by corpulentcoffee** [comment]
I'll make an issue and then close this.

**Comment by corpulentcoffee** [comment]
Replaced by #81 and #73.
