### ISSUE TITLE
Mismatch redirect url not a mismatch

### ISSUE THREAD

**Issue by vsoch** [globus/globus-cli#401]
Hi Globus! 

I have a native application, and am getting the message that the redirect url is not accurate:

![image](https://user-images.githubusercontent.com/814322/38468014-4ce7cfaa-3b0e-11e8-97a2-2418aed631bc.png)

However it is the first that I have in my list!

![image](https://user-images.githubusercontent.com/814322/38468009-358bad90-3b0e-11e8-8e1c-519b6b1ac259.png)

I then noticed that "it must be https" - I'm guessing this won't support local tools that the user is running (localhost) without https? So I switched to the default to use your https login portal, and created a login page that generates the url for the user and then the user enters it here to login, 

![image](https://user-images.githubusercontent.com/814322/38468863-d7b0af84-3b19-11e8-8d4e-6bc6f18a36c5.png)

but when I try the login I get a message about invalid scope:

![image](https://user-images.githubusercontent.com/814322/38468694-bdee3410-3b17-11e8-9cab-3e1384924bd6.png)

I'm not totally sure what is going on because my scope is like ones that have worked previously:

![image](https://user-images.githubusercontent.com/814322/38468721-ea844a0a-3b17-11e8-99aa-b568d13aedba.png)

And the strange thing is that the scope is showing to be the redirect url?

```html
<a href="https://auth.globus.org/v2/oauth2/authorize?client_id=056axxxxxxxx&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&state=_default&response_type=code.... etc.
```

I remember from a few previous times (when I am able to put in a https url) that scope was empty. So I just removed it from the url above... and that seems to work?

I think I'm either royally messing something up (and it's flying over my head like greased cheese) or there is a bug, or there is an intentional change of scope to prevent a client from doing what I'm trying to do. Regardless, I definitely need some help! With my hack, I get the code but then it's an invalid grant:

```
 File "/opt/conda/lib/python3.6/site-packages/globus_sdk/base.py", line 214, in post
    retry_401=retry_401)
  File "/opt/conda/lib/python3.6/site-packages/globus_sdk/base.py", line 387, in _request
    raise self.error_class(r)
globus_sdk.exc.AuthAPIError: (401, 'Error', 'invalid_grant')
```
I'm keeping the client that has started the flow stored with the application, but I think the bug primarily stems from here. I'd really appreciate help, I've been trying to debug this a few days and I'm starting to go looney (I've done this before and it worked fine!)

**Comment by vsoch** [comment]
Here is the broken code if it helps:

https://github.com/vsoch/interface/blob/add/globus/tunel/views/plugins/globus.py#L81

It bugs out in this function, when it has the code (I've dumped to pickle and confirmed the code itself is ok) and tells me about the invalid grant here:

https://github.com/vsoch/interface/blob/add/globus/tunel/views/plugins/globus.py#L176

 - app: references the flask application
 - globus_client: is the sregistry globus client (a controller to save tokens, etc.) that does the heavy lifting --> https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/globus/__init__.py
 - and then the _client attribute of globus_client is your python SDK transfer (native) client.

**Comment by jaswilli** [comment]
Hi @vsoch,

Sorry to hear you're having a hard time. I took a look at the errors you're getting and glanced at the code you linked to. A couple of things to get started:

Native app clients should definitely be able to use "localhost" redirect URIs with either `http` or `https`. You don't even need to explicitly add them when configuring the client, you just get to use them automatically. For an example you can check out https://github.com/globus/native-app-examples/blob/master/example_local_server.py and see that it uses `http://localhost` as its redirect.

I'm not sure what all you have going on in the "workaround" version of your flask app but I suspect the `invalid_grant` error message is because you're somehow reusing the authorization code in a new "flow" and the OAuth2 PKCE check is failing. The native app grant is special in that to get around not having a client secret it generates one-time challenges per auth flow and that challenge gets associated with the auth code that's returned after a successful authentication. If you take a code and plug it into a new flow I suspect it will blow up on you.

Also, I noticed you're attaching data, specifically the globus sdk client instances, to Flask's `app` object. That data will persist across multiple requests so trying to do authorization flows with "global" state like that is going to be problematic--it may very well be the source of your problem. If you want to stash per-request data somewhere, checkout `g` (`from Flask import g`).

Anyway, I'd like to focus on getting your app working with the `localhost` redirect as it seems that was your preference. If you could set up your app to do that again (and hopefully take care of the stashing data on `app` issue) we can try and troubleshoot that.

**Comment by vsoch** [comment]
Definitely! It's bedtime here but you've given me a ton to work with, and I'll report back after some more investigation. Thank you!!

**Comment by vsoch** [comment]
Hey @jaswilli ! Okay I've had another chance to go through these things, and think about the flow. This is actually an interesting use case because it's set up more like a protected server application (there is a web server inside a Docker image) that could easily run on a server and keep a client secret) but it's not, because the user generates it on the fly (and so we wouldn't save a client secret with it.)

> Native app clients should definitely be able to use "localhost" redirect URIs with either http or https. You don't even need to explicitly add them when configuring the client, you just get to use them automatically.

This is accurate - I retested the flow to use localhost as redirect uri, and it just worked. I'm honestly not sure why I was getting those errors the first time, but I think it's likely the many layers of clients I was using (more on this later).

> I'm not sure what all you have going on in the "workaround" version of your flask app but I suspect the invalid_grant error message is because you're somehow reusing the authorization code in a new "flow" and the OAuth2 PKCE check is failing.

I verified this by inspecting the globus client that makes the request vs. the globus client that is receiving it. What was happening is that in my init_globus_client I indeed was calling the function to initialize the authentication flow, and this is where the invalid grant came from, and it tricked me into thinking that the client state persisted.

> The native app grant is special in that to get around not having a client secret it generates one-time challenges per auth flow and that challenge gets associated with the auth code that's returned after a successful authentication. If you take a code and plug it into a new flow I suspect it will blow up on you.

This is what was happening. I think I had a few options here. I could try to stick my fingers into the globus python sdk and figure out where it's keeping those secrets, cache that, and then recreate the "same" client (I expect you wouldn't be in support of this) or I could do some hack in Flask or with a cache to try to save the same client. I didn't like this approach either because I can anticipate many bugs down the line with it, and looking at the code, it was getting weird and complex.

> Also, I noticed you're attaching data, specifically the globus sdk client instances, to Flask's app object. That data will persist across multiple requests so trying to do authorization flows with "global" state like that is going to be problematic--it may very well be the source of your problem. If you want to stash per-request data somewhere, check out g (from Flask import g).

I checked out g, but still had the same bug. I stepped back and decided to rethink this entirely.

**What I am working with**
 - The Singularity Global Client (sregistry) has a Globus plugin that is usable on the fly to work with a Globus endpoint. It does this via careful caching of tokens, and uses a Globus Native app client id. It works really well for command line because I can ask --> get --> retrieve refresh token on the first try, and then cache and be done. I don't need to worry about redirect and receiving the post.

**What I was trying to do**
 - The reason I was making it more complicated was to allow for tunel to use a different client id, which meant doing the flow over again, and sharing the same credential file.

**Why I was expecting it to work**
 - The Singularity Registry (server proper) uses an application with client secrets and this works totally fine, so I expected the same kind of flow to plug easily into a Native app implementation. I think it would per your sample app, but not easily in the weird setup I have with Flask and the client that is refreshed / reused being held by the server.

So here is what I did! I removed all the complexity by having the sregistry client used as it was intended. If the user tokens need to be updated (there is a function) they are shown this in the browser:

![image](https://user-images.githubusercontent.com/814322/38514774-1dcd9306-3c00-11e8-8c23-fed32a75d978.png)

Then on the command line the update is running one command to the container, see complete details on that in development docs here:

https://vsoch.github.io/interface/plugin-globus#commands

The script itself is simple and stupid, as it should be. It calls a function using the same server client that checks if the tokens need an update, and then issues a request for endpoints that will handle the flow and provide the user with the url, etc.

```python
#!/usr/bin/env python

from sregistry.main import get_client
import sys
...

    print('Updating Globus Client...')
    globus_client = get_client('globus://')
    if globus_client._tokens_need_update():
        globus_client._list_endpoints()
        print('Tokens updated!')
    else:
        print('Your tokens are up to date.')
```

And then the tokens are updated, we are using the sregistry client that the server already has installed without any weirdo stuff, and all is well until the user deletes the cache or otherwise mucks with it. Now when the user goes to the root globus portal in the tunel interface we have this working!

![image](https://user-images.githubusercontent.com/814322/38514178-6c770868-3bfe-11e8-9f3c-7f24d4f71059.png)

This should work well, and when/if someone complains about needing to use a command line I'll address this again then. This is also an edge case because the user is asked to do this step is done when the container is started (on the command line) and we would only hit this interface "your tokens need updating" very rarely.

Anyway, I'm happy with the fix, thanks for your insights!

**Comment by jaswilli** [comment]
Glad you got it working!
