### ISSUE TITLE
Should we write a curl-to-bash installer, serve from downloads.globus.org ?

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#411]
Thought about this a little bit over my morning coffee. Not sure if it's a good call or not.
Putting down my thoughts and not planning to work on this at all, obviously.

Problem 1:
- People have asked us for debs, rpms, and other packaging
- We don't have the time/hours to put together packaging builds for the CLI right now

Problem 2:
- Make CLI installs easier for novice users

Users have been acclimated to the arguably-dangerous-but-effective `curl ... | sudo bash -s` pattern.

I think it's well within our capabilities to write a short sh-compatible script which
- checks that required tools (python, virtualenv, pip) are installed
- checks if `id -u` is 0
- builds a virtualenv install either in `~/.globus_cli_virtualenv` OR `/Library/...` (Would that be right?) OR `/usr/local/lib/globus-cli/`
- links to the virtualenv `globus` wrapper (which activates the venv and invokes our CLI) from `/usr/local/bin` or `~/.local/bin` as appropriate
- If running under a user's account, can end with a terminal `which globus` to determine whether or not to print help about adding `~/.local/bin/`

The bigger question: is this a good idea? Should we do it?

**Comment by ericblau** [comment]
I would argue that novice users shouldn’t be installing non-native packages for system-wide installations, though a curl/bash script that installs to ~/.globus_cli_virtualenv might be useful to some, and seems pretty trivial to develop.

**Comment by sirosen** [comment]
We had some internal chatter about this too, which I'd like to record here.
To sum up...
- "It's good enough for homebrew"
- "I hate hate hate hate hate hate curl-pipe-to-sudo'd-bash installers" *hiss*
- Do we really need this anyway?
- `| bash` is much less offensive than `| sudo bash`

I personally think this is a lot less valuable if it's just for a non-system install because the instructions for that are pretty straightforward. It's knowing how to navigate your system python, or build a virtualenv linked from `/usr/local/bin/`, where I think such a script would be a value-add.


> I would argue that novice users shouldn’t be installing non-native packages for system-wide installations

This seems like a reasonable stance to me.
The things which spring to mind include
- what happens when/if it fails
- how will they uninstall
- what happens when/if users are confused by the changes

Maybe this all isn't worth thinking about too much and we should be thinking about native packaging (debs, rpms) instead. That carries a big build infrastructure cost, but pays dividends for our users in very simple, easy, safe installations.

**Comment by sirosen** [comment]
There's insufficient demand for this + we're now recommending `pipx`.
Closing.
