### ISSUE TITLE
Add testing for various Group related results and their rendering

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#418]
#417 brought this to my attention.

I don't even think we need to put any users in the group -- just an empty group will do fine.
Create a one-off group, and then add it to ACLs and roles during tests to make sure those render correctly.

The only trick of it is that since the group can be deleted or modified to cause test failures, it should probably belong to a Globus staff account.

**Comment by corpulentcoffee** [comment]
> I don't even think we need to put any users in the group -- just an empty group will do fine.

I don't think we even need to create the group. The Transfer API neither cares nor checks that a group UUID actually exists, and we're not querying Nexus here to render out its display name.

As far as the test suite goes, I think we would literally be fine generating a random UUID, adding a group role with it, and then checking that the role list renders it back with a webapp group URL.

**Comment by sirosen** [comment]
I finally did the testsuite rewrite I always talked about. But I feel no strong need to add testing for this right now, given 2+ years without another issue.

If a bug like #417 ever resurfaces I'll add something.
