### ISSUE TITLE
Remove `globus transfer endpoint autoactivate`

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#42]
Dan mentioned this to me.
Specifically, trying to autoactivate an activated endpoint which does not support autoactivate is confusing:

``` shell
$ globus transfer endpoint autoactivate --endpoint-id danielpowers#prod01
{
  "code": "AutoActivationFailed",
  "resource": "/endpoint/danielpowers%23prod01/autoactivate",
  ...
  "message": "The endpoint could not be auto activated, fill in the returned activation_requirements and POST them back to /activate to perform manual activation.",
  ...
  "oauth_server": null,
  "subject": null
}
```

Really, the autoactivate call in this case is unhelpful / unimportant, as the activation requirements document only applies if the `expires_in` field you get back is unacceptable.
autoactivate calls on autoactivate-capable endpoints works fine and has acceptable (but noisy) output.

Additionally, this call is generally unnecessary because we automatically attempt to autoactivate any endpoint which we see, so trying an `ls` or similar operation will result in an implicit and less scary looking autoactivation.

If we keep autoactivate as an explicit operation, we need to figure out better (textmode) output for it.
If we make it only magically autoactivate, this will feed into #30 as well.

**Comment by jaswilli** [comment]
I can't think of a use for `autoactivate` in the cli given that it's always going to do the autoactivate attempt behind the scenes.

Even having it output the activation requirements doesn't seem terribly useful since the cli is going to direct everyone to the web app to do endpoint activation.

I think maybe this issue should turn into "remove `transfer endpoint autoactivate` command?"

**Comment by sirosen** [comment]
The only counterpoint is that it might be desirable to autoactivate something for use with the SDK.
Not that that's a major use case, but I think that's why we added it.

Let's go ahead and remove it -- it's easy enough to restore later if desired.

**Comment by sirosen** [comment]
I got feedback from Dan that he's using `autoactivate` to check whether or not an endpoint requires a web activation flow.

In scripted use-cases, it's good to be able to check whether or not an endpoint will need activation within the expected timeframe of the script, and abort safely and early.
We need to make sure we continue to support that use case -- does that mean we have a course-adjustment on removing this, or that we do something else to handle that?

**Comment by sirosen** [comment]
We recently agreed on `is-activated` with a `--until TIME` option.
This rename will be included with the major name changing refactor.
