### ISSUE TITLE
Show latest version on output from --version

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#43]
If there's a reasonable way to do it, we could pull the latest published version from pypi, otherwise we could go by GitHub releases.

Example:
```
jasons-mbp:src jtw$ vagrant version
Installed Version: 1.8.6
Latest Version: 1.8.6
 
You're running an up-to-date version of Vagrant!
```

**Comment by sirosen** [comment]
The right thing to do is almost definitely to make a `get` call to `https://pypi.python.org/pypi/globus-cli/json`.
With `requests`:
```python
import requests
from distutils.version import LooseVersion
r = requests.get('https://pypi.python.org/pypi/globus-cli/json')
latest = str(max(LooseVersion(v) for v in r.json()['releases'].keys()))
```

`distuutils.version.LooseVersion` is stdlib, while `pkg_resources`, `packaging`, and even `setuptools` technically are not.
I don't want to deal with a complaint that our package fails to install without setuptools down the road.
(Come to think of it, we might be using `pkg_resources` in the SDK to handle the default config file. I think we should ideally fix that "someday" to not require that magic).

**Comment by sirosen** [comment]
Did a trial version of this (about to submit a PR), and got this as my initial output:
```shell
$ globus --version
Installed Version: 0.4.2.0
Latest Version:    0.4.0.0

You should update your version of the Globus CLI
```

Somewhat entertaining.
Doing a slight tweak to handle this, so no one complains about it in the future.
