### ISSUE TITLE
Work out a design for fetching release notes

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#433]
We need a way of fetching release notes for all of the releases between the current and upcoming revisions if we want `globus update` to show what's changing.

I've thought about a few ways of doing this, and they all have problems.

Basically, I see 5 sensible places for us to put changelog data for this feature:
- In pypi.org , by adding a changelog to the `long_description` field and ensuring that we can parse it
- In downloads.globus.org , where it can be whatever format is convenient (multiple txt files, single JSON file, etc), e.g. `downloads.globus.org/cli/changelog.json`
- In the CLI repo's `master` branch, where it should probably be a single file (probably JSON to ease parsing)
- docs.globus.org , potentially as a JSON or flat text file alongside `docs.globus.org/cli/reference/changelog`
- In GitHub Releases descriptions, which can be fetched via tag after versions are pulled from pypi data

The options wherein we need the data to be non-json but parseable or recognizable in some way are bound to be fragile. That basically rules out pypi , but not the other options.

I also feel nervous about relying on `https://github.com/globus/globus-cli/raw/master/changelog.json` or somesuch -- if we move the repo or change things around in the future, this seems pretty limiting.
It's unlikely that we'll change hosting or anything in the foreseeable future, but I'd like not to sow problems for us into the future. This could also be a problem for GitHub Releases. I'd be more comfortable with Releases, a dedicated feature for this purpose, than a flat file of our own design, which we might move or remove (on purpose or by accident).

docs.globus.org and downloads.globus.org are under our control, and the only downside I can see is
- for docs.globus.org, you need your PR to merge for new docs to be uploaded
- for downloads.globus.org, we'd need to distribute credentials to CLI devs for uploading a new changelog to S3

Both seem fine to me -- and better than trying to build on top of pypi -- and then I guess it's a question of what @jaswilli, @shifflett-globus, and @aaschaer prefer?
I'd consider docs.globus.org, downloads.globus.org, and GitHub Releases to all be in the running.
Or is there some other place we could put our changelog to keep it parseable which I'm missing?

**Comment by jaswilli** [comment]
I was thinking that we would use the GitHub API to pull the release `description`, although I'm open to other options if someone has a convincing argument.

We should be able to easily fetch everything we need up to and including the actual text of the release description (i.e., changelog):

```json
{
    "name": "v1.7.0",
    "description": "Enhancements:\r\n- Add the `--no-default-directory` flag to `globus endpoint create` and `globus endpoint update` which unsets the default directory setting (#428)"
}
```
We should basically just be able to render `description` as-is to the console.

**Comment by sirosen** [comment]
I'd be perfectly happy with GitHub releases for this. The other ideas were thoughts kicking around in my head, but not all ideas are good ideas.

I'd want to make it part of the process that a release gets tagged and pushed to GitHub, and properly marked as a release, before the push to pypi. I don't think that's a tall order. I'm closing this (question/discussion item) in favor of an new issue to actually do it.
