### ISSUE TITLE
Recursive dir listing has potentially dangerous implications service-side -- limit it or remove it

### ISSUE THREAD

**Issue by sirosen** [globus/globus-cli#46]
The case we're concerned about is the pathological case of hundreds of nested directories expanding to huge numbers of files (m/billions).
Per notes from Karl, we'd need to switch traversal to be breadth-first and unbuffered output to handle that case at all -- makes perfect sense, though unbuffered JSON output will require careful handling and some testing to ensure that the results are valid JSON.

To resolve, we have three paths forward (there may be more?):
- Remove recursive `ls` from the CLI
- Add it to the SDK and limit the total number of dirs to `ls` to some "small" but reasonable number -- e.x. 50
- Add it to the SDK and enforce an N second sleep every M dirs, where N and M are both small (guessing 1s every 25 dirs)

This is only worth discussing as an SDK addition (and not purely as a CLI feature) because we've made it very easy to build your own version of recursive `ls`.
Unless we make it easier to use the "correct" version than to build your own, we haven't actually solved the problem.

Removing it from the CLI is viable but may be worse than adding a `recursive=True` option to the SDK `ls` -- I just don't trust that people won't go building this themselves. It therefore seems a poor way of protecting the service.

Given the choice between a hard limit and a sleep, the sleep has much better semantics.
It doesn't mess with error modes at all -- an SDKLimitExceeded error will be confusing to people, and is likely to break scripts unexpectedly as their inputs scale up.
The sleep behavior also sets the tone correctly for a future universe in which that kind of rate limiting is enforced service side in addition to being done client-side.

There's already been some discussion of these, but I'm moving it into issues to better track status and decisions.
I'd appreciate input from @karlito-go and @ranantha on this one.

**Comment by tuecke** [comment]
We will likely be adding recursive listing with wildcards to the endpoints.  Perhaps leave the current recursive support for now, and then we will improve it when this endpoint feature is added.
