### ISSUE TITLE
RFE: Support later versions of jmespath 0.9

### ISSUE THREAD

**Issue by akkornel** [globus/globus-cli#461]
Hello!

I am looking at how hard it would be for Globus to be ported to FreeBSD, and I found two dependency issues that would need to be addressed, with click and jmespath.

jmespath has a hard dependency on version 0.9.2, but that version is not available in FreeBSD-land right now: FreeBSD 11 has 0.9.3 as a package, and the ports tree has version 0.9.4.

I did a quick check on the jmespath changelog, and 0.9.3 and 0.9.4 only seem to be bugfix releases.  So, I was wondering if it is possible for the jmespath dependency to be changes to `jmespath>=0.9.2,<1.0`?

There is also an upcoming issue with click: The details on why not to change the dependencies were already covered in #453, so I won't rehash it here.  As an FYI, FreeBSD 11 ships with a 6.7 version of click, but the latest version available in the ports tree is 7.0.  So, not an issue right now.

**Comment by sirosen** [comment]
I'm a little bit confused about what's being asked here.

> ... that version is not available in FreeBSD-land right now ...

I'm not sure how this is relevant to the CLI? It's a python package, so if you `pip install` it, you should be pulling package versions from pypi.
Are you trying to build a native FreeBSD package from an sdist or similar?

If you install the CLI into a separate virtualenv, I think that's *much* more likely to be successful than trying to reconcile it with various platform requirements. e.g.
```shell
virtualenv --python=python3 /opt/globus/cli_venv
source /opt/globus/cli_venv/bin/activate
pip install globus-cli
ln -s /opt/globus/cli_venv/bin/globus /usr/local/bin/globus
```

And that way you get an isolated install of globus-cli, available via `/usr/local/bin/` with no system package conflicts.

**Comment by xylar** [comment]
I would also concur that having more recent versions of `jmespath` supported would be helpful.  Currently, `0.9.2` has not been built for python 3.7 on conda-forge, meaning that `globus-cli` cannot be installed with conda-forge and python 3.7.  I'm going to ask for a `noarch` build of `jmespath` 9.2.0 but it's much easier to maintain `globus-cli` as part of a larger python ecosystem if the dependencies remain relatively current.
