### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by jrwrigh** [globus/globus-cli#472]
I get the following error when trying to install the application using Python 3.4:

```bash
$ pip install --upgrade --user globus-cli
Collecting globus-cli
  Using cached https://files.pythonhosted.org/packages/0f/69/422adbafc9468fd485cb4a9c9eb0788b21c1693d2ff82654c1ba17a3eaa8/globus-cli-1.10.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /software/python/3.4/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1zc00qz/globus-cli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1zc00qz/globus-cli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-c1zc00qz/globus-cli/
    Complete output (1 lines):
    error in globus-cli setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tried running `pip install --upgrade --user setuptools` as had been suggested in other similar issues (with other software packages), but I still get the same error.

**Comment by jrwrigh** [comment]
My cluster distribution has the luxury of loading several different versions of python. Moving to 3.6.6 allowed the installation to work. Not sure what the original issue was.

**Comment by sirosen** [comment]
The only times I've seen this have been with really old versions of setuptools. If you still have the old environment still available, I'd be happy to talk over how to dig around to see if the wrong version of setuptools is being loaded.

**Comment by jrwrigh** [comment]
I just reloaded the environment, but it appears to be working now. Maybe it was referencing an older version of setuptools for some reason. Or I needed to reload environment variables to get the reference correct.
