### ISSUE TITLE
globus login, add output describing result/action after entering Authorization code

### ISSUE THREAD

**Issue by stumartin** [globus/globus-cli#52]
The login command could be improved with some additional explanation for what happened after the Authorization code is entered.  Below is a sample suggestion.

```
globus login
Please login to Globus here:
  https://auth.globus.org/v2/oauth2/authorize?code_challenge=<snip>

Enter the resulting Authorization Code here: <snip>

A credential (use appropriate term) for using the CLI was saved for you in (path).  It is valid until <date/time>

> (back at command prompt)
```

**Comment by sirosen** [comment]
I'm very glad I asked for your suggestion, rather than writing it up myself.
The last bit suggests to me that we should wait to do this until we have #38 done. Then we can say
"It is valid indefinitely, but you can revoke it at any time by running `globus logout`".

**Comment by sirosen** [comment]
With #120 now in progress, I think it's worth now doing this.
