### ISSUE TITLE
Transfer: support "-a" option on endpoint ls

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#55]
Current behavior shows all files by default. Desired behavior is to not show dotfiles by default but provide a flag (e.g. `-a`).

**Comment by sirosen** [comment]
I'd like every short option to have a corresponding long option, as I think that's part of making helptext and options easily grok-able.

If we're following `ls` conventions, that's `-a, --all`. Alternatives include things like `-a, --show-hidden` and `-a, --all, --show-hidden`.

Should we make it `-A` to make it even more uniform with GNU ls? That might be overly picky, and lots of people don't use `-A` anyway.
