### ISSUE TITLE
Transfer: review output from task show

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#56]
Do we want to hide certain fields from the output? Example: `event_link` and `subtask_link`?

**Comment by sirosen** [comment]
I don't think any fields should ever be hidden from JSON output.
However, for the text output we almost always want to be a bit more discerning.

We'll use the colon formatted output, and I think it's okay if the text output is very restrictive (status, type, deadline, and a few other things).

**Comment by corpulentcoffee** [comment]
I think the `globus task show` output we have today is OK and I don't think we should bother hiding anything from `--format=json`. Do we want to keep this issue open?

**Comment by sirosen** [comment]
Nope. At least as of your comment, the output has been reviewed.

Thanks much!

**Comment by jaswilli** [comment]
I don't care much but a case could be made for hiding `subtask_link` from the JSON output since support for subtasks has been removed the transfer api (a year and a half ago!).

**Comment by corpulentcoffee** [comment]
Maybe we should just open a Transfer issue on that one rather than `del`ing the key from the response object.

**Comment by jaswilli** [comment]
I considered doing that last week when I made this discovery. I'll do it now since fixing it (or at least getting an explanation) upstream is definitely better. 👍

**Comment by jaswilli** [comment]
https://github.com/globusonline/koa/issues/42
