### ISSUE TITLE
globus endpoint set-subscription-id fails with TypeError

### ISSUE THREAD

**Issue by tcooper** [globus/globus-cli#569]
## Summary

I was recently added as a subscription manager to our campus subscription. I am administrator on a campus endpoint. I tried to use latest `globus-cli` to add the subscription to the endpoint and was unable to do so.

### Globus CLI Version

```
~ ❯ globus version
Installed version:  3.0.2
Latest version:     3.0.2
```

### Globus CLI Command Failure

```
~ ❯ globus endpoint set-subscription-id c982d486-6d04-11e5-ba46-22000b92c6ec 6cb69fd5-a845-11e7-aeab-22000a92523b
TypeError: put() takes 2 positional arguments but 3 were given
```

#### globusid.org identity

```
~ ❯ globus session show
For information on your primary identity or full identity set see
  globus whoami

Username             | ID                                   | Auth Time
-------------------- | ------------------------------------ | --------------------
tcooper@globusid.org | c4ba56ec-d274-11e5-b96b-aba7fa6fae46 | 2021-10-08 09:31 PDT
```

#### campus identity

```
~ ❯ globus session show
For information on your primary identity or full identity set see
  globus whoami

Username                                  | ID                                   | Auth Time
----------------------------------------- | ------------------------------------ | --------------------
046f34cb4575a6c40145afbe435f0530@ucsd.edu | 9d81ec52-198b-403b-b90a-efdf6c1d0561 | 2021-10-08 10:22 PDT
```

New auths were generated for each identity attempted.

*NOTE: Campus contact who provided the subscription ID reported the same failure.*

**Comment by sirosen** [comment]
We've just released CLI v3.1.0 . It includes some new features which we had in `main` as well as this bugfix.

Please let me know if this isn't sorted out after an upgrade.
