### ISSUE TITLE
Transfer: task wait behavior (e.g. status code)

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#59]
- ~~Polling interval (#31)~~
- Make sure `--heartbeat`  behavior is what is expected
- Existing CLI progress bar shows `...` if we are still directory scanning. Not sure if the rest-api exposes that info (nr_directory_expansions_pending)
- Make sure exit status is doing what is expected (currently a "cancel" returns `1`, existing CLI returns `0`)

**Comment by sirosen** [comment]
I think the biggest thing to pick out and make sure is correct is the exit behavior.

Right now it does `exit(0)` if the task does not terminate, and does `exit(1)` if it does terminate.
We could invert those or do something else.

**Comment by sirosen** [comment]
Agreement in parameter styles discussion was that these exit codes should be flip-flopped, and mildly adjusted for unsuccessful task termination:
- if task terminates during waiting window, `exit(0)`
- if task does not terminate, `exit(1)`
- if task terminates with `status != SUCCESS`, `exit(1)`

As a future feature, we can map task statuses the way that `--map-http-status` is planned.
