### ISSUE TITLE
Update documentation for batch transfer

### ISSUE THREAD

**Issue by BJWiley233** [globus/globus-cli#594]
FYI the [documentation for batch transfer](https://docs.globus.org/cli/reference/transfer/) is CONFUSING:

The examples given such as:
1. stdin `globus transfer $source_ep $dest_ep --batch -`
gives
`Error: Got unexpected extra argument (-)`
`cat transfer.txt | globus transfer $source_ep $dest_ep --batch -` gives same error
2. filename `globus transfer $source_ep $dest_ep --batch transfer.txt`
gives
`Error: Got unexpected extra argument (transfer.txt)`

In the documentation you have `--batch FILENAME` and if you have this in the documentation it better take a file.  If you get an error taking in a file you **MUST** update the documentation.

**Comment by rudyardrichter** [comment]
Hi @BJWiley233, could you please include the output from `globus version`? I wonder if you may be running a previous version of the CLI, and the behavior of `--batch` changed in the 3.0 release; the docs reflect the most recent version.

**Comment by BJWiley233** [comment]
aww man it's way old 2.1.0.  sorry will update!
