### ISSUE TITLE
Verify that we're handling encoding (utf8) correctly

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#65]
Comment from Karl:

> What is the byte/unicode encoding on mkdir/rename/transfer/ls paths.  What if a path is illegal utf8.

**Comment by jaswilli** [comment]
Notes from Karl:

> $ globus transfer ls  --endpoint-id 5d3c6c59-5244-11e5-84dd-22000bb3f45d --long
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

> $ globus transfer endpoint my-shared-endpoint-list --endpoint-id 5d3c6c59-5244-11e5-84dd-22000bb3f45d   # go#ep on my dev box
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-10: ordinal not in range(128)

> $ globus transfer endpoint show  --endpoint-id 5d3c6c59-5244-11e5-84dd-22000bb3f45d
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

> $ globus transfer task list  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Could be the “command” field is blowing it up because I used the old CLI transfer command with a non-ascii path

**Comment by sirosen** [comment]
I think those notes come from before I changed the table printing code to be at least mildly unicode-friendly.

We should do a comprehensive evaluation, and see if we can get these errors out of things that do the colon-formatted text output.
