### ISSUE TITLE
Globus search ingest task id not listed in tasks 

### ISSUE THREAD

**Issue by byee4** [globus/globus-cli#745]
```
 globus search ingest -v f6ba6555-76cb-436e-b746-7fce96bf6ecf test_metadata.json
Task ID:      897e4f99-a517-405d-9c95-6feca56234e7
Acknowledged: True

(jupyter) [bay001@tscc-1-0 ~]$ globus task list
does not display task id as expected
```
[test_metadata.txt](https://github.com/globus/globus-cli/files/10395452/test_metadata.txt)

**Comment by sirosen** [comment]
This is expected, but I understand that it may be surprising or confusing.
The command you are looking for is `globus search task list`.

`globus task list` preceded the existence of the Globus Search service. It uses the [Globus Transfer Task List API](https://docs.globus.org/api/transfer/task/#get_task_list) to list your Globus Transfer tasks.

I'm somewhat tempted to close this as an "invalid" issue, but at the same time that doesn't seem like a good resolution for the fact that Globus Transfer commands have a kind of primacy in the CLI which may not be appropriate anymore. I'll discuss this with our team to think about how we can make things clearer in the future.

**Comment by byee4** [comment]
Ahh I see. Thanks for clarifying!
