### ISSUE TITLE
Feature request: add support for Fig autocomplete 

### ISSUE THREAD

**Issue by schudelg** [globus/globus-cli#751]
Fig.io provides tools for automatically generating autocomplete specs for tools built with a variety of tools (including click). Would be really nice to have support for autocompletion (and possibly suggestions). 

See [https://fig.io/docs/guides/autocomplete-for-internal-tools](https://fig.io/docs/guides/autocomplete-for-internal-tools)

[https://github.com/withfig/autocomplete](https://github.com/withfig/autocomplete)

**Comment by kurtmckee** [comment]
Hello Gary! [Globus CLI supports CLI completion for Bash and Zsh](https://docs.globus.org/cli/#tab-completion). Does this meet your needs?

**Comment by sirosen** [comment]
I don't think we'll be working on this unless there are signs of much greater demand.

Aside: I think it is the responsibility of any "post-bash, post-zsh" shell to meet the existing tooling ecosystem where it is.
