### ISSUE TITLE
Argument parsing issue with --batch

### ISSUE THREAD

**Issue by AlecThomson** [globus/globus-cli#786]
Hi there,

I've hit an issue running `globus transfer` - there seems to be an issue with the argument parsing when `--batch` is provided. For example, running:
```
globus transfer --batch=$FILE_DIR/files.txt $SRC_UUID:$SRC_DIR/ $DST_UUID:$DST_DIR/
```
Gives the following error
```
Usage: globus [OPTIONS] SOURCE_PATH DEST_PATH
Try 'globus --help' for help.

Error: Missing argument 'DEST_PATH'.
```
Thanks for your help with this

**Comment by sirosen** [comment]
Hi there! This bug report slipped through the net, sorry about that.

I think that what's happened here is that the batch file you've supplied is missing an argument on one of its lines. As a result, parsing the file (which is a mini CLI parse) fails and prints this error.

I think the error in this case is ambiguous and could easily be improved in a couple of ways, to clarify the source and also direct you to the failing line.
