### ISSUE TITLE
Required options should become positional arguments

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#81]
e.g. `globus transfer bookmark show --bookmark-id=<UUID>`
should become `globus transfer bookmark show <UUID>`.

Requires #73 for commands that deal with endpoints and paths to simplify the interface of some commands (e.g. `globus transfer async-transfer`, which without any simplification would require four positional arguments instead of two).

**Comment by corpulentcoffee** [comment]
Also:
Use same treatment for optional options for commands for which no other positional argument would make sense.

e.g. `globus transfer endpoint search --filter-fulltext=go#ep1`
should become `globus transfer endpoint search go#ep1`
even though `globus transfer endpoint search --filter-scope=shared-by-me` is valid

e.g. `globus transfer task cancel --task-uuid=<UUID>`
should become `globus transfer task cancel <UUID>`
even though `globus transfer task cancel --all` will be valid (#60)

**Comment by sirosen** [comment]
Some questionable items are surfacing as I chug through this.
Lots of them result from the create/update duality. Those options look *very* similar, but change what is and is not required.

- Endpoint Creation
```shell
$ globus transfer endpoint create \
    --endpoint-type [globus-connect-personal|globus-connect-server|s3] ...
```
Should endpoint-type really become a positional? Or should it become truly optional, defaulting to `globus-connect-server` or `globus-connect-personal`?
A positional Choice type seems really awkward/weird to me.

What about `display_name`? Right now it's required on creation, but that mismatches with endpoint update. (Same holds for shared endpoints).

- Role Creation
```shell
$ globus transfer endpoint role create ENDPOINT_ID \
    --role ... \
    --principal ... \
    --principal-type ...
```

All four of those things are required, but asking people to memorize the order seems like a bit of a stretch. Maybe these are better off as required options?

- ACL Add
```shell
$ globus transfer endpoint acl add-rule ENDPOINT_ID:PATH \
    --permissions ... \
    --principal ... \
    --principal-type ...
```

As above, this seems like too many.
It also raises the common pairing of principal-type and principal value. Perhaps something like the `ENDPOINT_ID:PATH` notation would be appropriate for those?
It's hard for me to make an argument for `group(<UUID>) | identity(<UUID>)` when this is a problem with a general and natural solution when we consider that we own our own URN space.

- ACL Update
```shell
$ globus transfer endpoint acl update-rule ENDPOINT_ID RULE_ID PERMISSIONS
```
This seems fine, given that we go with a high-level identifier, a more specific identifier, and then a value.
However, it should presumably match up well with `acl add-rule`. Does that argue for making it `--permissions` (required), or `PERMISSIONS` for both?

- Endpoint Server Add
```shell
$ globus transfer endpoint server add ENDPOINT_ID \
    --hostname ...
```
This looks fine to change to `HOSTNAME`, but it's kind of weird to write `HOSTNAME --scheme gsiftp` -- the order on that looks wrong.
We could accept `gsiftp://HOSTNAME` and `ftp://HOSTNAME`, with a default of `gsiftp` when no scheme is given. Does that work well?
We also need to consider `globus transfer endpoint server update`.

**Comment by sirosen** [comment]
A secondary note on why positional choices are odd: they can be expressed as a level in the command tree.
That is, there's not much difference between ` create gcp|gcs` and `gcp|gcs create`.

Phrased the other way around, every command in a structured CLI like this is a positional choice, so treating them as parameters is a little confusing.

**Comment by corpulentcoffee** [comment]
Additionally, per 10/24 meeting for ACLs and roles:

- `--principal-type=` and `--principal=` become `--identity XXX`, `--group XXX`, `--anonymous`, etc
- (ACLs) `--permissions` default to `r` [maybe]
