### ISSUE TITLE
Globus login failed with ImmatureSignatureError

### ISSUE THREAD

**Issue by miaoneng** [globus/globus-cli#820]
Hi Globus Team. I was trying to install globus-cli as "pip install globus-cli". I installed it in a clean virtualenv. However, when I login with `globus login`, it throws out ImmatureSignatureError

I tried both with and without "--no-local-server" option, and I also have personal connected endpoint software installed locally. 

```
(.venv) jtang@DESKTOP-96VLFMB:~/globus$ globus login
You are running 'globus login', which should automatically open a browser window for you to login.
If this fails or you experience difficulty, try 'globus login --no-local-server'
---
(.venv) jtang@DESKTOP-96VLFMB:~/globus$ globus login --no-local-server
Please authenticate with Globus here:
------------------------------------
------------------------------------
Enter the resulting Authorization Code here:
ImmatureSignatureError: The token is not yet valid (iat)
```

Could you advise?

**Comment by sirosen** [comment]
I have two things that will help us track this down. Could you do each of the following?
- Check and confirm that your system clock is close to true time, and isn't very far back in time.
- Run this again with `--debug` and share the output, i.e. `globus login --no-local-server --debug`

I haven't seen this particular error before, but my immediate instinct is that this is a JWT validation error due to clock drift.
Running with `--debug` will get us a lot more info on exactly what happened here.

I'm also going to do a little bit of research on how JWT validation behaves.

**Comment by sirosen** [comment]
Thanks for that detail, it confirms the suspicion that this is `pyjwt`-related.
Running this down, it seems that our tolerance for clock drift between the client and server is `0`! (The `pyjwt` default.)
I find it somewhat surprising that we don't see this as a frequent issue -- but I'm talking with our team about how best to resolve.

I'm working on a fix for this issue to allow us to increase tolerance via `globus-sdk`, and then we will need to update `globus-cli` to set that tolerance value. I'll update this ticket when we have released a fix.

In terms of workarounds in the meantime, the only idea which springs to mind is to modify CLI source to add a 0.5s sleep before the token is decoded. I'd only like to get into the details of that if you need to get login working while we sort out the fix.

**Comment by sirosen** [comment]
Hi there! We've been discussing your case within our team a little to try to decide on a reasonable value to crank this up to.
Our previous fix made the tolerance being tunable, so now it's really just a matter of picking and setting a value, and then releasing that fix.

We've done a little bit of research and we're tending towards a 64s interval, which matches some prior art and is in the category of "big enough for days without a clock sync on modern hardware, but small enough that we're not discarding the validation entirely".
I'll drop another update here when we do a release.

**Comment by sirosen** [comment]
There was a long delay before we were able to release this fix -- an unfortunate side-effect of our team trying to balance a number of concerns within the CLI codebase.
However, we finally have a release out as of today with a more lenient leeway for JWT validation.

Please let me know if you continue to see issues!
