### ISSUE TITLE
globus transfer --exclude : Can I exclude sub directories?

### ISSUE THREAD

**Issue by Nitin123-4** [globus/globus-cli#850]
Hi All,
I am using globus transfer command to transfer data.

I have 2 question:

1. Is it possible to transfer a symbolic link? If yes please provide any specific parameter. I have Latest version: 3.16.0 installed.
2. How to use --exclude command to exclude subdirectory: Example: A/B So I don't want to upload B subdirectory. 

Thanks.

**Comment by kurtmckee** [comment]
Hello @Nitin123-4!

1. Symlink behavior within the Transfer service is [documented in the Frequently Asked Questions](https://docs.globus.org/faq/transfer-sharing/#how_does_globus_handle_symlinks). That document does a better job of describing the behavior than I can, but I'll summarize that:

   When transferring a directory recursively, the Transfer service will not transfer symlinks. However, if the source directory is _itself_ a symlink to another directory, that source directory symlink will be followed, and the linked directory's contents will be transferred.

   When transferring a file, if the source file is a symlink then the linked file's contents will be transferred as a regular file to the destination.

2. `--include` and `--exclude` behavior are documented in [the `globus transfer` command documentation](https://docs.globus.org/cli/reference/transfer/#include_and_exclude). The inclusions and exclusions are evaluated in the order they appear on the command line, so to exclude `A/B`, you will need to first specify `--exclude A/B` and then `--include *`:

    ```
    globus transfer ... --exclude A/B --include * ...
    ```

    Typically, a sentence like "I want to transfer everything _except_ xyz" will translate to a command with `--exclude xyz` listed first, followed by `--include *`.

    A sentence like "I _only_ want to transfer xyz" will translate to a command with `--include xyz` listed first, followed by `--exclude *`.

Please let me know if you have additional questions!

**Comment by sirosen** [comment]
I hope that between Kurt's explanation and the link out to the docs site, this provides enough information.
Remember, you can always check the helptext for any command with `--help`, and we're happy to answer questions here in GitHub issues or via support@globus.org.

For now, I'm going to close this as resolved.
