### ISSUE TITLE
globus-timer job status command produces misleading output

### ISSUE THREAD

**Issue by tcooper** [globus/globus-cli#866]
**Describe the bug**
When using `globus-timer` CLI to create a recurring daily transfer configured to end after `n_days` the job status display suggests the job will continue to run but it does not.

**To Reproduce**
1. Schedule a `globus-timer` job with `--stop-after-runs` value specified
2. Allow `globus-timer` job to complete all expected runs
3. Review `globus-timer` job status
4. See misleading output below...

```
~/globus ❯ globus-timer job list
Name                     | Job ID                               | Status | Last Result
-------------------------|--------------------------------------|--------|-------------
expanse-slurm-accounting | 0e89b262-19a0-495d-a408-8582e6fc8571 | loaded | RUN COMPLETE
```

```
~/globus ❯ globus-timer job status 0e89b262-19a0-495d-a408-8582e6fc8571
Name:            expanse-slurm-accounting
Job ID:          0e89b262-19a0-495d-a408-8582e6fc8571
Status:          loaded
Start:           2021-06-03T19:00:00+00:00
Interval:        1 day, 0:00:00
Next Run At:     2021-07-06T19:00:00+00:00
Last Run Result: RUN COMPLETE
```

*NOTE: `Next Run At:` field suggests job will run again but it is past its specified `--stop-after-runs` value.*

```
{
  "name": "expanse-slurm-accounting",
  "start": "2021-06-03T19:00:00+00:00",
  "interval": 86400.0,
  "callback_url": "https://actions.automate.globus.org/transfer/transfer/run",
  "callback_body": {
    "body": {
      "source_endpoint_id": "b256c034-1578-11eb-893e-0a5521ff3f4b",
      "destination_endpoint_id": "de22d598-71ff-11eb-a9ad-efda19b7c028",
      "transfer_items": [
        {
          "source_path": "/expanse/lustre/projects/sds185/bnk_svc/expanse/accounting",
          "destination_path": "/expanse/accounting",
          "recursive": true
        }
      ],
      "label": "EXPANSE Slurm Accounting Logs to XDMoD",
      "sync_level": 3,
      "encrypt_data": true,
      "verify_checksum": true,
      "preserve_timestamp": true
    }
  },
  "scope": null,
  "stop_after": {
    "date": null,
    "n_runs": 30
  },
  "job_id": "0e89b262-19a0-495d-a408-8582e6fc8571",
  "status": "loaded",
  "next_run": "2021-07-06T19:00:00+00:00",
  "results": [
    {
      "data": {
        "action_id": "Fz35r5haHXTf",
        "completion_time": "2021-06-30T19:00:00.944297+00:00",
        "creator_id": "urn:globus:auth:identity:c4ba56ec-d274-11e5-b96b-aba7fa6fae46",
        "details": {
          "code": "ActivationRequired",
          "description": "Failed to activate endpoint b256c034-1578-11eb-893e-0a5521ff3f4b",
          "required_scope": null,
          "resolution_url": "https://app.globus.org/file-manager?origin_id=b256c034-1578-11eb-893e-0a5521ff3f4b"
        },
        "display_status": "INACTIVE",
        "label": null,
        "manage_by": [],
        "monitor_by": [],
        "release_after": "P30D",
        "start_time": "2021-06-30T19:00:00.944266+00:00",
        "status": "INACTIVE"
      },
      "errors": null,
      "status": 202,
      "ran_at": "2021-06-30T19:00:03.368682"
    },
    ...<snip>...
  ]
}
    
```

**Expected behavior**
`globus-timer job status` command should indicate the job will not ever run again after it passes one of it's `stop_after` conditions, either `date` or `n_runs` or both. Ideally, it would also indicate which `stop_after` parameter had been reached (both if they both had).

**Versions:**
 - Python: 3.6.8
 - globus-timer-cli: 0.2.5

**Comment by sirosen** [comment]
_As part of our efforts to spin down the `globus-timer-cli` project and ensure that all of its functionality has been ported forward, we're moving this issue to `globus-cli`._

We're re-evaluating this in the new context of `globus timer show` and some service-side updates which have been made since this was filed. It may or may be resolved already, but we think there's at least one minor update which will be needed before we can close this out. More info to come!

**Comment by ada-globus** [comment]
Following up: `status` was added to the supported fields for timer jobs [in v3.17.0](https://github.com/globus/globus-cli/pull/855). This should be resolved now!

**Comment by ada-globus** [comment]
(@tcooper Please feel free to reopen if we've missed anything here)
