### ISSUE TITLE
Batch mode and paths?

### ISSUE THREAD

**Issue by corpulentcoffee** [globus/globus-cli#89]
Either

- forbid it by changing the guards for async-delete and async-transfer to accept only batch mode exclusive-or path
- make it so the path specified on the command line is prepended to each line of the batch input (which might have corner cases like path normalization issues)

Today, the path from the command line is thrown in with the paths input on the batch input, which is at best not helpful or at worst will lead to unexpected behavior.

**Comment by sirosen** [comment]
I want to make sure that we remember, if we pursue the prepend behavior, that there are questions about what's allowed and normalization.
- do we allow base paths like `../../`?
- if a path is absolute, do we still join it to the base path? (Probably not?)

**Comment by corpulentcoffee** [comment]
As need to clean-up help text that is currently arguably ambiguous, e.g. what does "include" mean:

```
  --batch                   Accept a batch of paths on stdin (i.e. run in
                            batchmode). Uses ENDPOINT_ID as passed on the
                            commandline, and includes any commandline PATH
                            given
```
